구글 로그인 및 회원 가입, jwt 생성 및 발급
RE-BON/ReBoN pull request #120
Opened 2022-04-16 16:20 UTC by PyeongGangKim

### Description
- 구글 로그인 및 회원 가입 진행.
- jwt 생성 및 발급
- jwt 발급 시 authorization header에 넘겨주었음.
- OauthHandler test는 naver와 kakao도 완성되면, parameterizedTest로 진행할 예정.
- 구글 로그인, 회원 가입 인수테스트 완성 후 rest docs에도 추가

### Trouble Shooting

### ETC
- 후에 naver, kakao도 진행할 예정

2022-04-22 08:35 UTC, KJunseo requested changes
고생 많으셨네요!! 리뷰 늦어서 죄송합니다!
양이 많고 로직이 복잡해서 리뷰하는 것도 오래걸리네요! 빼먹은 부분이 있을수도 있는데 다음 리뷰 요청때 다시 살펴보겠습니다!

코멘트 남긴 부분이랑 이 부분을 한 번 같이 생각해보시면 좋을 것 같아요!
1. 현재 구조에서 새로운 Provider가 들어오게 된다면, OauthProvider, application.yml, xxxRequester, xxxUserInfo 가 추가되어야 할 것 같아요. 변경점이 조금 많다는 생각이 들어요. 이 부분을 줄일 수 있지 않을까요? 내부 중복도 생길 것 같아요.

2. 현재 xxxRequester 클래스에서 외부 api 요청이 이루어지고 있는데 provider가 추가되면 xxxRequester 클래스들 끼리 중복 로직이 많이 생길 것 같아요.

2022-04-22 08:35 UTC, KJunseo commented on .gitmodules
> +	branch = be/feature/signup
branch 부분을 추가해주면 해당 브랜치를 기준으로 submodule을 업데이트하게 되는 것으로 알고 있어요.(아마 security repository 기준)

그래서 be/feature/signup 라고 해놓으면 해당 브랜치가 없어서 작동하지 않지 않나요??

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/presentation/AuthController.java
> +    public ResponseEntity login(@PathVariable String oauthProvider, @RequestParam String code) {
반환값이 없어도 <Void>로 타입 명시 해주는게 좋아보입니다

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/presentation/AuthController.java
> +        String bearerToken = JwtUtils.makeBearerType(response.getToken());
개인적으로 controller는 요청을 받고 응답만 전달해주는 역할이 맞다고 생각해요.
토큰을 만드는 과정은 다른 레이어의 역할이라고 생각합니다.

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/presentation/AuthController.java
> +                             .header("Authorization", bearerToken)
Authorization 헤더는 클라이언트 -> 서버로 요청할 때 사용하는 헤더라고 알고 있어요.

클라이언트에게 토큰을 전달할때는, 쿠키나 body로 넘겨주는 건 어떤가요?

MemberController도 확인 부탁드립니다!

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/application/AuthService.java
> +    private final JwtUtils jwtUtils;
클래스 네이밍을 보면 util클래슨데 왜 주입을 받지? 라는 생각이 들어요. 빈으로 주입을 받길 원하면 네이밍을 바꿔주는건 어떤가요? 

진짜 Util 클래스의 역할만 한다면 인스턴스화를 막고, JwtUtils.xxxx()로 메서드만 사용하는 게 맞다고 생각합니다!

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +
두 줄입니다!

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +    public OauthUserInfo getUserInfoByCode(final String code) {
어떤 메서드의 매개변수에는 final을 붙이고 어떤 곳에는 붙이지 않는데 특별한 이유가 있나요??

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +                                                    .orElseThrow(UnableToGetTokenResponseFromGoogleException::new);
사실 이 부분은 저도 예전에 사용했을 때 잘못 사용했던 경험이 있어요.
WebClient를 사용할 때 block()이나 toStream() 같은 메서드를 사용하면 webclient를 사용하는 이점이 없다고 하더라고요. 비동기 방식 코딩을 해본적이 없어서 저도 감이 안 오긴 하네요. 

사실 또 이 메서드 같은 경우는 외부 서버에 보내는 api 요청이 2개이지만, 두 번째 api 요청은 첫 번째 api 요청의 결과값으로 처리해야하고, 그 외에 또 오래 걸리는 로직은 없다고 생각이 들어서 상관없을 것 같다는 생각도 들긴합니다. 그냥 아래 글 읽어보면 좋을 것 같아서 참고용으로 남겨드립니다. 읽고 의견 남겨주시면 감사하겠습니다!!

- https://tecoble.techcourse.co.kr/post/2021-10-20-synchronous-asynchronous/
- http://tech.pick-git.com/webflux/

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/exception/oauth/UnableToGetTokenResponseFromGoogleException.java
> +public class UnableToGetTokenResponseFromGoogleException extends OauthException {
이 예외 클래스 이름이 너무 긴 것 같다는 생각이 들어요. 또 어떤 소셜 로그인이 실패했는지 각각 예외를 두는 것이 좋을지, 그냥 공통적으로 예외를 두는게 좋을지 얘기해보면 좋을 것 같아요

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/exception/oauth/ErrorResponseToGetAccessTokenException.java
> +public class ErrorResponseToGetAccessTokenException extends OauthException {
access_token이 제대로 넘어왔는지를 검증할때 발생하는 예외인 것 같습니다.
ErrorResponse라는 단어가 필요한지 잘 모르겠어요

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +    }
왜 access token을 받아오지 못했는지 에러 메세지도 넘어오는 걸로 알고 있는데 그 메세지를 사용해서 예외를 던져줘도 좋을 것 같네요.(구글도 넘어오는지는 잘 모르겠습니다..)

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/application/AuthService.java
> +        Member member = memberRepository.findByEmail(email, oauthProvider)
메서드 명만 봐서는 email로만 멤버를 찾아올 것 같아요!

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/Member.java
>          this.profile = profile;
실제 값을 할당하는 생성자는 하나만 두고 나머지는 주생성자를 호출하는 식으로 처리하는 게 좋을 것 같아요

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/Profile.java
> +    }
사용하지 않는 메서드인 것 같습니다!

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/repository/MemberRepository.java
> +    Optional<Member> findByEmail(@Param("email") String email, @Param("oauthProvider") OauthProvider oauthProvider);
오 String이 아니라 Enum으로 넘겨도 JPQL로 쓸 수 있나보네요!

2022-04-22 08:35 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/auth/AuthAcceptanceTest.java
> +        ExtractableResponse response = login(google.name(), authorizationCode);
타입을 명시해주는 게 좋아보입니다.
```suggestion
        ExtractableResponse<Response> response = login(google.name(), authorizationCode);
```

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/exception/oauth/NoSuchOAuthMemberException.java
> +        super("소셜 로그인 회원이 아닙니다. 회원가입을 진행합니다.", HttpStatus.NOT_FOUND);
로그인 실패시 401 코드가 더 맞지 않을까요???

2022-04-22 08:35 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/auth/AuthAcceptanceTest.java
> +        Map responseBody = response.body().as(Map.class);
타입을 명시해주는 것이 좋아보입니다.

```suggestion
Map<String, Object> responseBody = response.as(new TypeRef<>() {});
```

2022-04-22 08:35 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/auth/AuthAcceptanceTest.java
> +                .willReturn(GoogleUserInfo.from(Map.of("email", testEmail)));
이렇게 직접 mocking 하는 것은 인수테스트라고 보기 어려운 것 같아요. 외부 api 서버 로직이 있을 때 mocking을 하려면 mockserver를 사용하는 게 좋아보입니다!

- https://tecoble.techcourse.co.kr/post/2020-09-30-mocking-server/

2022-04-22 08:35 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/shop/ShopReadAcceptanceTest.java
> +ShopReadAcceptanceTest extends AcceptanceTest {
```suggestion
class ShopReadAcceptanceTest extends AcceptanceTest {
```

2022-04-22 08:35 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/auth/AuthIntegrationTest.java
> +    void loginSameEmailInvalidOauthProviderException() {
동일한 이메일 다른 제공자면 회원가입이 가능하지 않나요???

2022-04-22 08:35 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/JwtUtils.java
> +public class JwtUtils {
util 클래스로 사용할거라면 util 패키지에 두는 게 좋다고 생각해요.
그게 아니라면 클래스 명 변경 후 infrastructure가 맞는 것 같아요!

2022-04-25 04:50 UTC, PyeongGangKim commented on .gitmodules
> +	branch = be/feature/signup
제가 gitmodule를 쓰는 방법을 잘 몰랐네요,,, 좀 더 찾아볼게요!!

2022-04-25 04:50 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/presentation/AuthController.java
> +    public ResponseEntity login(@PathVariable String oauthProvider, @RequestParam String code) {
void말씀하시는 거 맞죠?

2022-04-25 04:51 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/presentation/AuthController.java
> +        String bearerToken = JwtUtils.makeBearerType(response.getToken());
그렇군요,,,!! 다른 레이어에서 처리하도록 하겠습니다!!

2022-04-25 04:51 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/presentation/AuthController.java
> +                             .header("Authorization", bearerToken)
쿠키에 넣는 것을 한번 찾아봐야겠네요!!

2022-04-25 04:52 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/application/AuthService.java
> +    private final JwtUtils jwtUtils;
네이밍을 바꾸는 쪽으로 하는 게 맞겠네요!!

2022-04-25 04:52 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +    public OauthUserInfo getUserInfoByCode(final String code) {
제가 일괄적으로 final을 썼다가 지우는 작업을 했었는데, 이 부분은 못 지웠나보군요,,,

2022-04-25 06:11 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/auth/AuthAcceptanceTest.java
> +                .willReturn(GoogleUserInfo.from(Map.of("email", testEmail)));
한번 보고 적용해보도록 할게요!! 감사합니다!!

2022-04-25 06:22 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/exception/oauth/NoSuchOAuthMemberException.java
> +        super("소셜 로그인 회원이 아닙니다. 회원가입을 진행합니다.", HttpStatus.NOT_FOUND);
로그인에 관한거니까 401이 맞겠네요!!

2022-04-25 12:18 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/auth/AuthIntegrationTest.java
> +    void loginSameEmailInvalidOauthProviderException() {
회원가입을 할 수 있도록하는 exception 입니다! email은 등록되어 있지만, oauthProvider는 등록이 되어 있지 않은 것이기 때문에, exception을 주어, 회원 가입을 하도록  하는 테스트입니다!

2022-04-28 11:17 UTC, KJunseo requested changes
고생하셨습니다! 조금 더 의견 나눠보면 좋을 것 같아서 리뷰 남겼습니다!
확인 부탁드려요!

2022-04-28 11:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +        Map<String, Object> userInfo = ApiRequester.getUserInfo(code, tokenUri, clientId, secretId, redirectUri, userInfoUri);
매개변수가 너무 많다는 생각이 들어요.
클린코드에서도 이런 주제 이야기가 나오는데 한 번 찾아보면 좋을 것 같아요

2022-04-28 11:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/repository/MemberRepository.java
> +            @Param("oauthProvider") OauthProvider oauthProvider);
findBy~ 같은 메서드들은 spring data jpa가 만들어줄텐데 직접 JPQL을 적어주신 이유가 있을까요?

2022-04-28 11:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/Profile.java
> +    }
할당 작업은 주생성자에서만 하고 부생성자는 주생성자를 호출하는 식으로 하는건 어떤가요?

2022-04-28 11:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/domain/GoogleUserInfo.java
> +public class GoogleUserInfo implements OauthUserInfo {
provider마다 xxxUserInfo를 만드는 것 보다, 위에 만들어두신 Enum(OauthProvider)을 통해 같이 관리하는건 어떤가요? 현재 변경점이 enum, xxxRequester, xxxUserInfo, yml 4군데인데 변경점을 조금 줄일 수 있지 않을까요? 의견이 궁금합니다.

2022-04-28 11:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +    private String userInfoUri;
이 부분은 xxxRequester 마다 중복되는 건가요??

2022-04-28 11:17 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/auth/AuthAcceptanceTest.java
> +
```suggestion

```

2022-04-28 14:34 UTC, gomster96 requested changes
수고하셨습니다. 한가지 궁금한 사항이 있어서 답변 부탁드립니다. 또한 나중에 requester도 여러개 생길 것 같은데, infrastructure 내부의 class들 중 공통적인 기능을 하는 class들은 infrastructre내에 새로 패키지를 만들어서  묶어주면 더 좋지 않을까 생각됩니다.!

2022-04-28 14:34 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/member/presentation/MemberController.java
> +    }
오.. 이렇게 생성되었다고 .created로 HTTP에 상태값을 넣어주며 ResponseEntity를 보낼수 있네요.

2022-04-28 14:34 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/auth/application/AuthService.java
> +        String email = userInfo.getEmail();
이 부분에서 userInfo responseBody를 만들어서 보내주는데 서비스 단의 코드를 보면 단순히 email조회로만 사용하는것 같습니다.  나중에 userInfo를  쓰실 예정인건가요? 아니면 어떤 기능을 염두하고 reponseBody를 반환하게끔 만드신건지 궁금합니다.

2022-04-28 16:59 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/application/AuthService.java
> +        String email = userInfo.getEmail();
responseBody는 이제 구글에서 유저에 대한 정보를 Map형태로 받아온 것 입니다. 바로, map에서 원하는 것을 뺏어 쓰는 것 보다 객체로 만들어서 객체에 message를 보내, email을 얻어오는 게 좀 더 객체 지향스럽다고 생각하여 이렇게 구현했습니다!!

2022-04-28 17:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/domain/GoogleUserInfo.java
> +public class GoogleUserInfo implements OauthUserInfo {
그 방법도 좋을 거 같고, 지금 생각해보니 xxxUserInfo를 각각 둘 필요도 없다고 생각이 드네요,,
OauthUserInfo 하나만 두어도 괜찮을 거 같다는 생각이 듭니다!! 제안하신 방법도 좀 더 고민해보고 더 좋은 것을 적용해보도록 할게요!!

2022-04-29 02:52 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +    private String userInfoUri;
@Value로 들어가는 값들이 달라서, 각각 넣어줘야 될 거 같아요!!

2022-04-29 11:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +    private String userInfoUri;
`@ConfigurationProperties`를 사용해서 collection으로 받는 방법은 어떤가요?

2022-04-29 11:39 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/GoogleRequester.java
> +    private String userInfoUri;
준서님이 작성하신거 보고, 그 방법이 좀 더 좋은 거 같아서 찾아보고 있습니다!! 감사합니다:)

2022-04-30 06:58 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/member/domain/repository/MemberRepository.java
> +            @Param("oauthProvider") OauthProvider oauthProvider);
email이 embedded type인 Profile안에 있는 필드이다 보니까, findByEmailAndOauthProvider로 작성하면 만들어주지 않고, 앞에 embedded type을 명시해줘야 되네요!! findByProfileEmailAndOauthProvider

https://stackoverflow.com/questions/24441411/spring-data-jpa-find-by-embedded-object-property

2022-04-30 10:47 UTC, KJunseo approved these changes
이만 머지하겠습니다! 복잡한 로직인데 고생하셨습니다!
추가적인 부분은 네이버 카카오 적용한 후 리뷰에서 하면 될 것 같네요! 코멘트 남긴것만 확인해주세요!

2022-04-30 10:47 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/repository/MemberRepository.java
> +    Optional<Member> findByProfileEmailAndOauthProvider(String email, String oauthProvider);
아 이건 저도 첨 알았네요. 네이밍이 길어지는 걸 보니 처음 하신 방법이 더 나은 것 같다는 생각도 드네요. 편한대로 하시면 될 것 같습니다!

2022-04-30 10:47 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/ApiRequester.java
> +    public static Map<String, Object> getUserInfo(String code, OauthProvider oauthProvider) {
이 클래스 내부 메서드들을 static으로 만드신 이유가 있나요??

2022-04-30 11:04 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/auth/application/AuthService.java
> +        String email = userInfo.getEmail();
아 그렇군요 감사합니다!

2022-04-30 11:09 UTC, gomster96 approved these changes
제가 잡을 부분은 없는 것 같습니다. 수고 많이하셨습니다 멋지네요 ㅎㅎ

2022-04-30 11:48 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/ApiRequester.java
> +    public static Map<String, Object> getUserInfo(String code, OauthProvider oauthProvider) {
메소드들이 인스턴스 변수를 사용하지 않고, 인스턴스 생성에도 의존하지 않는 메소드라고 생각되서 static으로 만들었습니다!!

이런 경우에는 static을 없이 사용하는 게 좋은가요??

2022-04-30 11:54 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/ApiRequester.java
> +    public static Map<String, Object> getUserInfo(String code, OauthProvider oauthProvider) {
개인적으로는 유틸성이 아니라면 static을 안쓰는게 좋다고 생각합니다. 유틸 느낌은 아닌 것 같다는 생각이 들기도 해서 의견이 궁금하네요.

static 객체지향 등으로 검색해보시면 좋을 것 같아요.

2022-04-30 11:55 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/ApiRequester.java
> +    public static Map<String, Object> getUserInfo(String code, OauthProvider oauthProvider) {
넵 한번 찾아보겠습니다!!

2022-04-30 15:19 UTC, merged