feat[#6]: 태그 삭제 기능
RE-BON/ReBoN pull request #152
Opened 2022-05-03 06:20 UTC by leehyelim0691

### Description
태그 삭제 기능

### Trouble Shooting

### ETC

2022-05-03 07:07 UTC, KJunseo requested changes
리뷰 남겼습니다!
확인후 다시 요청주세요!

2022-05-03 07:07 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
메서드 참조로 간단하게 나타낼 수 있을 것 같아요
```suggestion
    public void deleteShopTag() {
        this.shopTags.forEach(ShopTag::deleteShopTag);
    }
```

2022-05-03 07:07 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/ShopTag.java
> +    }
커밋전 포맷팅을 적용하면 좋을 것 같네요!

```suggestion
    public void deleteShopTag() {
        this.deleteContent();
    }
```

2022-05-03 07:07 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
저번 회의 때 삭제하려는 태그 하나만 가진 shop이 있을 경우 예외처리를 해주기로 했던 기억이 있는데 이 부분 처리가 없는 것 같아요!

2022-05-03 07:07 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +                .collect(Collectors.toList());
현재 포맷팅이 다르게 적용되어 있는 것 같아요. 저번에 카톡으로 공유해드렸던 포맷팅을 적용하면 좋을 것 같습니다!

2022-05-03 07:07 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagDeleteIntegrationTest.java
> +        System.out.println(createdShopTags);
print 구문은 지우는 게 좋을 것 같습니다!

2022-05-03 07:07 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagDeleteIntegrationTest.java
> +    public void deleteTagAndShopTag() {
특정 태그 삭제 후, 해당 태그를 가지고 있는 shop을 조회했을 때, 삭제된 태그가 가져와지지 않는지도 검증하면 좋을 것 같아요

2022-05-03 07:56 UTC, PyeongGangKim requested changes
고생많으셨어요:)
리뷰 남겼습니다 확인부탁드려요!!

2022-05-03 07:56 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +        Tag tag = findById(id);
TagService 안에 있는 method이기 때문에, 메서드 명에 Tag가 들어가지 않고, delete만으로 표현해줘도 괜찮을 거 같아요!!

2022-05-03 07:56 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
이 부분도 Tag안에 있는 거니까? delete라고 메서드 명을 써도 괜찮지 않을까요?

2022-05-03 07:56 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/tag/TagDeleteIntegrationTest.java
> +
여기서 이 구문이 들어가야되는 이유가 있나요??

2022-05-03 17:41 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
좋은 의견 감사합니다!

2022-05-03 17:46 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/ShopTag.java
> +    }
앗 네 감사합니다!

2022-05-03 17:47 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +                .collect(Collectors.toList());
네 감사합니다!

2022-05-03 17:48 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagDeleteIntegrationTest.java
> +        System.out.println(createdShopTags);
앗 네 깜빡했네요 감사합니다!

2022-05-03 17:48 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +        Tag tag = findById(id);
좋은 의견 감사합니다!

2022-05-03 17:49 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
네! 감사합니다!

2022-05-04 01:59 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
네 감사합니다 추가하도록 하겠습니다!

2022-05-06 04:48 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagDeleteIntegrationTest.java
> +    public void deleteTagAndShopTag() {
좋은 의견 감사합니다!

2022-05-06 05:27 UTC, PyeongGangKim requested changes
고생하셨습니다!!
리뷰 남겼습니다 확인하시고 다시 요청주세요:)

2022-05-06 05:27 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/ShopTag.java
> +        }
getShop 메소드를 사용하지 않고, 동일한 클래스에 있는 field이기 때문에 그냥 가져다쓰면 될 거 같고, getter로 shopTag를 꺼내오는 것보다 메시지를 보내 처리하는 게 좋아보여요!

2022-05-06 05:27 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +        });
저번에 준서님이 메소드참조로 하는 게 좋을 거 같다고 말한 거 같은데 그 부분이 반영이 안되어 있는 거 같아요!!

2022-05-06 07:12 UTC, KJunseo requested changes
리뷰 남겼습니다! 확인 후 요청주세요

2022-05-06 07:12 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/ShopTag.java
> +        }
평강님 의견에 동의합니다. 그리고 포매팅도 여전히 적용되지 않은 것 같아요

2022-05-06 07:12 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagDeleteIntegrationTest.java
> +        List<Tag> createdShopTags = Arrays.asList(createdTag);
리스트에 하나만 넣는 경우 아래 2가지를 대신 사용하는건 어떤가요
- List.of
- Collections.singletonList

2022-05-17 00:55 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/ShopTag.java
> +        }
좋은 의견 감사합니다!

2022-05-17 00:56 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +        });
앗 깜빡했네요 감사합니다!

2022-05-17 00:56 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/ShopTag.java
> +        }
네 감사합니다!

2022-05-17 01:08 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagDeleteIntegrationTest.java
> +        List<Tag> createdShopTags = Arrays.asList(createdTag);
좋은 의견 감사합니다!

2022-05-17 14:18 UTC, KJunseo requested changes
로직상 궁금한 부분이 있어 리뷰 하나 남깁니다 
확인 후 다시 요청주세요!

2022-05-17 14:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +    }
shop의 shopTag가 아니라 Tag의 shopTag가 하나인 경우에 검증해야하지 않나요?

2022-05-17 14:29 UTC, KJunseo approved these changes
approve하겠습니다 리뷰 남긴 부분만 한 번 확인하시고 반영하거나 의견달아주시면 좋을것같네요

2022-05-17 14:29 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +    }
메서드명이 delete여서 삭제가 일어날 것 같은데 메서드 내용은 검증만 일어나기 때문에 validates~~ 와 같은 네이밍을 사용하는 건 어떤가요?

2022-05-17 15:50 UTC, PyeongGangKim approved these changes
approve하겠습니다~!!
고생많으셨어요:)

2022-05-18 04:12 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +    }
앗 좋은의견 감사합니다!

2022-05-18 04:33 UTC, gomster96 approved these changes
수고하셨습니다 ㅎㅎ

2022-05-18 04:35 UTC, merged