[#142]: 닉네임 중복 확인 여부
RE-BON/ReBoN pull request #154
Opened 2022-05-04 09:01 UTC by PyeongGangKim

### Description
- 닉네임 중복 확인 여부. 성공시 200 OK, 중복 시 400 BadRequest
- 중복 체크 uri를 어떻게 해야할 지 잘 모르겠네요,, 그 부분 같이 고민해주시면 좋을 거 같아요!!
- 그리고 중복 시 400 BadRequest를 보냈는데, 찾아보니 409 conflict로 하는 곳도 있더라고요, 제 생각에는 이 api는 생성을 하는 것이 아니고,
체크만 하는 것이라고 생각해서 400 BadRequest로 했는데, 그 부분에 대한 의견도 듣고싶어요!!

### Trouble Shooting

### ETC

2022-05-04 13:59 UTC, gomster96 approved these changes
깔끔한거 같습니다. 수고하셨습니다.

2022-05-05 04:27 UTC, KJunseo requested changes
몇 부분 리뷰 남겼습니다! 확인 후 다시 요청해주세요

2022-05-05 04:27 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/presentation/MemberController.java
> +    @PostMapping("/members/nickname/duplicate") //TODO 어떤 uri가 맞을지 얘기
https://changrea.io/Web/rest-api-design-1/#uri-resource-archetypes 이 부분 처럼 http method 만으로 나타낼 수 없다면 동사도 써도 된다고 생각합니다.(controller)

duplicate 뜻이 복사하다 인 것 같아서 지금 생각해보니 문법적으로 맞는지는 모르겠지만 /check-duplicate 같은 건 어떤가요? 뭐가 나은지 잘 모르겠네요

2022-05-05 04:27 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberCreateAcceptanceTest.java
>      private ExtractableResponse<Response> saveMember(MemberCreateRequest memberCreateRequest) {
이 메서드가 여기뿐만 아니라 AuthAcceptanceTest에도 있는 것 같아요. 여러군데에서 사용할 수 있는 메서드는(ex. 로그인) 하나만 만들어놓고 가져다 쓰는 식으로 사용하는게 좋을 것 같아요

2022-05-05 04:27 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberCreateAcceptanceTest.java
>      private ExtractableResponse<Response> saveMember(MemberCreateRequest memberCreateRequest) {
이 메서드가 여기뿐만 아니라 AuthAcceptanceTest에도 있는 것 같아요. 여러군데에서 사용할 수 있는 메서드는(ex. 로그인) 하나만 만들어놓고 가져다 쓰는 식으로 사용하는게 좋을 것 같아요

2022-05-05 04:27 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberCreateAcceptanceTest.java
> +    void checkDidNotDuplicateNickname() {
이 부분에 대한 rest docs가 없는 것 같아요

2022-05-05 04:27 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberCreateAcceptanceTest.java
> +    void checkDidNotDuplicateNickname() {
이 부분에 대한 rest docs가 없는 것 같아요

2022-05-05 05:18 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/member/presentation/MemberController.java
> +    @PostMapping("/members/nickname/duplicate") //TODO 어떤 uri가 맞을지 얘기
그게 좀 더 좋을 거 같네요!!!

2022-05-06 04:14 UTC, KJunseo approved these changes
이만 approve 하겠습니다! 궁금한 점이 하나 있어 코멘트 달았는데 그 부분만 답변해주시면 될 것 같습니다!

2022-05-06 04:14 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/AcceptanceTest.java
> +        RequestSpecification spec = new RequestSpecBuilder()
혹시 이렇게 변경하고 Util 클래스를 만들어서 사용하신 이유가 있나요? 궁금해서 여쭤봅니다!

2022-05-06 05:05 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/AcceptanceTest.java
> +        RequestSpecification spec = new RequestSpecBuilder()
리뷰받은 것 중에 중복되는 메소드인 saveMember나 login같은 것을 한 곳에서만 만들고, static 메소드로 공유해서 사용하기 위해서, 따로 Util클래스를 두었습니다. 
기존처럼 AcceptanceTest클래스에서 값을 가지고 RequestSpecification을 가지고 있다면, 공통되는 메소드를 static 메소드로 만들 수 없어서 이렇게 만들었습니다.

2022-05-06 13:17 UTC, merged