Be/feature/authorization
RE-BON/ReBoN pull request #161
Opened 2022-05-13 08:43 UTC by PyeongGangKim

### Description
- Interceptor와 custom annotation 사용해서 @RequiredLogin가 붙은 uri은 authorization header에서 token을 추출하고, token의 유효성을 검사한다.
- HandlerMethodArgumentResolver를 사용하여, @Login어노테이션이 붙은 parameter에 LoginMember 객체를 넣어준다.
- 테스트를 위해, shop에 대한 review를 가져오는 api만 구현했고, 후에 review api를 완성할 예정.

### Trouble Shooting
- token을 만들 때, claims로 key, value 형태로 payload를 넣어줬는데, 원하는 방식대로 payload가 들어가지 않아, claims를 미리 만들어 놓고, token을 build할 때, setClaims를 사용하여 payload를 넣어줬다.

### ETC

2022-05-15 05:49 UTC, KJunseo requested changes
몇 가지 궁금한 점 남겼습니다!
로그인이 필요한 acceptance test 들에 로그인 과정도 추가해주면 좋을 것 같네요

2022-05-15 05:49 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/domain/LoginMember.java
> +    Long id;
접근제한자를 default로 하신 이유가 있나요?

2022-05-15 05:49 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/JwtProvider.java
> +    }
만료시간 확인 등의 작업은 따로 해주지 않아도 되나요?

2022-05-15 05:49 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/LoginInterceptor.java
> +package com.handong.rebon.auth.infrastructure;
인터셉터를 infrastructure 레이어에 두신 이유가 있나요?
저는 요청 전/후 처리라는 생각이 들어서 presentation 레이어라는 생각이 드는데 이유가 궁금합니다!

2022-05-15 05:49 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/LoginInterceptor.java
> +    }
preflight 처리도 해주면 좋을 것 같아요!

2022-05-15 05:49 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/LoginMemberArgumentResolver.java
> +package com.handong.rebon.auth.infrastructure;
여기도 infra에 두신 이유가 궁금합니다!

2022-05-15 05:49 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/config/WebConfig.java
> +    private final LoginInterceptor loginInterceptor;
생성자 주입 받으신 이유가 있나요?
argumentResolver는 메서드 내에서 주입해주는데 인터셉터는 다르게 해주셔서 궁금해서 여쭤봅니다

2022-05-15 05:49 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/controller/auth/AuthorizationInterceptorTest.java
> +public class AuthorizationInterceptorTest extends ControllerTest {
혹시 테스트의 목적이 무엇일까요? 
만들어진 모든 api에 대해서 테스트가 있는 게 아니라 몇 가지 api만 있어서 어떤 기준으로 진행하셨는지가 궁금합니다!

2022-05-15 06:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/JwtProvider.java
> +    }
만료시간이 JwtException에 포함된다하여, 만료시간도 결국 유효하지 않은 토큰이기 때문에, 같이 처리했습니다!!

2022-05-15 09:17 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/domain/LoginMember.java
> +    Long id;
앗,,제가 private으로 설정을 안했군요,,,

2022-05-15 09:35 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/auth/infrastructure/LoginInterceptor.java
> +package com.handong.rebon.auth.infrastructure;
제가 ddd에 대한 이해가 좀 부족해서, infrastructure에 넣은 거 같습니다,,,다시 좀 고민해보고 적용할게요!!

2022-05-15 09:39 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/config/WebConfig.java
> +    private final LoginInterceptor loginInterceptor;
음,,,그 부분은 딱히 이유가 없었네요,,,하나로 통일하는 게 좋을 거 같네요!!

2022-05-15 09:40 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/controller/auth/AuthorizationInterceptorTest.java
> +public class AuthorizationInterceptorTest extends ControllerTest {
Interceptor가 잘 작동되는 지를 테스트를 하기 위해서, 만들었습니다. 잘 작동되는지를 판단하는 데 모든 api를 다 테스트 안해도 되지 않나 싶어서 몇가지만 작성했습니다!!

2022-05-16 15:24 UTC, KJunseo approved these changes
고생하셨습니다! 
실제 검증이 필요한 api 들은 다른 issue로 처리하신다고 하니 이만 Approve 할게요!

2022-05-17 03:14 UTC, gomster96 approved these changes
이젠 커스텀 어노테이션까지... 굉장하십니다. 수고 많이하셨습니다!

2022-05-17 16:09 UTC, merged