자동완성 기능 구현
RE-BON/ReBoN pull request #162
Opened 2022-05-16 15:13 UTC by KJunseo

### Description
자동완성 기능 구현 
- 검색창에서 글자를 입력할 때 마다 해당 글자와 연관 있는 태그 목록을 반환해준다.
- 검색어는 매우 자주 입력될 수 있으므로 매번 DB와의 connection을 통해 태그 목록을 조회하는 것은 비효율적이기 때문에 ElasticSearch를 사용하였다.
- 한글 자음/모음 분리를 위해 플러그인을 적용하였다(https://github.com/netcrazy/elasticsearch-jaso-analyzer)
- 검색어가 포함된 태그 목록 반환
- 초성으로도 검색가능
- 한글 검색은 자음, 모음을 모두 분리해서 보내줘야한다. ex) 한동대 -> ㅎㅏㄴㄷㅗㅇㄷㅐ
- 테스트는 testcontainer를 사용하였습니다.

ex) tags = ["북구", "남구"]
1) keyword = "ㅂㅜ" => results = ["북구"]
2) keyword = "ㄱㅜ" => results = ["북구", "남구"]
1) keyword = "ㄴㄱ" => results = ["남구"]

실행 방법
1) Dockerfile 생성
```docker
FROM elasticsearch:7.16.2

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/netcrazy/elasticsearch-jaso-analyzer/releases/download/v7.16.2/jaso-analyzer-plugin-7.16.2-plugin.zip
```

2) 실행
```
docker build --tag elasticsearch-custom .

docker run -p 9200:9200 -p 9300:9300 --name elasticsearch-custom -e "discovery.type=single-node" elasticsearch-custom
```

### Trouble Shooting
- LocalDateTime 호환 안되는 문제
  - es는 기본적으로 데이터를 넣어놓고 꺼낼때 parsing을 하는 듯한데, LocalDateTime을 호환해주지 않는다.
  - 호환해주는 Instant를 사용하거나 @Field 를 통해 formatting을 해주면 된다.

- Jpa와 ElasticSearch 같이 쓰는 경우 ApplicationContext 로드 실패(Bean 주입 과정에서 repository가 중복되기 때문)
  - @EnableElasticsearchRepositories은 Elasticsearch관련 repo만, @EnableJpaRepositories는 JPA 관련 repo만 관리하도록 설정

- testcontainer 설정 
  - testcontainer를 사용하여 테스트를 진행하였는데 es를 사용하지 않는 테스트들이 정상 동작하지 않는 문제
  - es를 도입하면서 관련 설정 때문에 ApplicationContext 로드 실패
  - es를 사용하지 않는 테스트들에 @EnableAutoConfiguration(exclude = ) 와 @MockBean을 통해 es 관련 설정이 아무 일을 하지 않게 처리

*테스트의 경우 기존 AcceptanceTest를 상속받아 처리하고 싶었으나 es 설정 관련 문제로 인해 따로 생성하여 rest docs 설정 부분에서 중복이 발생하였는데 좋은 방법이 있을지 궁금

### ETC
- elasticSearch 개념: https://tecoble.techcourse.co.kr/post/2021-10-19-elasticsearch/
- testcontainer 개념: https://medium.com/riiid-teamblog-kr/testcontainer-%EB%A1%9C-%EB%A9%B1%EB%93%B1%EC%84%B1%EC%9E%88%EB%8A%94-integration-test-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0-4a6287551a31
- testcontainer 공식 문서: https://www.testcontainers.org/modules/elasticsearch/

2022-05-17 15:42 UTC, PyeongGangKim requested changes
elasticsearch에 관한 것을 처음 해보셨을 텐데 구현 잘하셨네요!!
궁금한 것들 리뷰 남겼습니다!! 확인하시고 다시 리뷰 요청해주세요:)

2022-05-17 15:42 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/config/JpaConfig.java
> +}
JpaConfig를 따로 빼두신 이유가 있나요??

2022-05-17 15:42 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/AcceptanceTest.java
> +    private TagSearchRepository tagSearchRepository;
안쓰는 거 같아요!!

2022-05-17 15:42 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/IntegrationTest.java
> +
사용되지 않고 있어요!!

2022-05-17 15:42 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/domain/repository/CustomTagSearchRepositoryImpl.java
> +}
이 부분은 searchByName으로 메서드를 만들어주면, data jpa에서 만들어주진 않나요?

2022-05-17 15:42 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/util/StringUtil.java
> +    }
메서드 명을 strip이 아닌 trim으로 하신지 궁금합니다!

2022-05-17 15:42 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/config/TestElasticSearchConfig.java
> +    }
test와 실제 구동할 때 elasticsearch가 올라가있는 container의 port를 동일한 것을 사용하는데 이때, 발생할 문제점은 없나요?

2022-05-17 15:52 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/config/JpaConfig.java
> +}
다른 config 들도 따로 빼서 적용되어 있어서 일관성있게 처리하려고 분리했습니다.

2022-05-17 15:52 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/AcceptanceTest.java
> +    private TagSearchRepository tagSearchRepository;
이 부분은 ES 자동설정을 적용하지 않기 위해 가짜 Mock으로 등록한 것입니다. 이 부분을 빼면 테스트가 정상동작하지 않습니다.

2022-05-17 15:52 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/IntegrationTest.java
> +
이 부분도 마찬가지입니다!

2022-05-17 15:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/domain/repository/CustomTagSearchRepositoryImpl.java
> +}
SearchHits 같은 부분은 spring data elasticsearch 에서 제공해줍니다!
대신 `findByNameContains(String name)` 이런식으로는 작성할 수 있을 것 같습니다. 이 부분이 더 좋다고 생각하시나요?

2022-05-17 15:58 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/util/StringUtil.java
> +    }
trim이 공백을 제거한다는 느낌이 더 강해서 그렇게 처리했습니다! 근데 strip()을 결국 사용하니 strip이 더 나은 것 같기도 하네요.
strip이 더 낫다고 생각하시나요?

2022-05-17 15:58 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/config/TestElasticSearchConfig.java
> +    }
이 부분은 9200 포트를 사용하는 것이 아니라 비어있는 포트 중 랜덤한 포트를 띄우고 9200에 매핑되어 있는 실제 배정받은 랜덤 포트를 가져오는 로직입니다!

2022-05-17 16:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/util/StringUtil.java
> +    }
제 의견은 strip이 더 낫다고 생각합니다:)

2022-05-17 16:03 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/domain/repository/CustomTagSearchRepositoryImpl.java
> +}
findByNameContains라면, search라는 동사가 들어가는 게 좀 더 메서드가 하는 일을 잘 표현해주는 거 같네요!!
searchByKeyword가 좋은 거 같습니다!

2022-05-19 07:38 UTC, gomster96 requested changes
정말 수고하셨습니다. 또한 PR에서 참고하셨던 좋은 내용의 블로그들도 올려주신 덕분에 코드를 이해하는데 너무 큰 도움이 되었습니다. 저도 엘라스틱 서치에 관해 많이 배운것 같아서 감사합니다. 한가지 궁금한 점이 있어서 해당 것만 답변해주시면 어프로브하겠습니다. 

PR에서 보면 초성검색(한동대 -> ㅎㄷㄷ)이 아닌  가 아닌 자모분해(한동대 -> ㅎㅏㄴㄷㅗㅇㄷㅐ)로 하시려고 계획하셨던거 같은데 초성검색으로 바꾸신 이유가 있을까요??

-- 검색해보니 엘라스틱 서치에서 자모 분해 기능을 하는 plugin도 있다는것을 알게 되었습니다. https://renuevo.github.io/elastic/autocomplete/elastic-autocomplete-2/

2022-05-19 07:38 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/acceptance/tag/TagElasticSearchAcceptanceTest.java
> +            .withEnv("discovery.type", "single-node");
이렇게 Testcontainer를 사용하는군요.. 👍

2022-05-19 15:56 UTC, PyeongGangKim approved these changes
저는 궁금한 점들이 해결됐습니다!! 처음 구현하시는 것일 텐데, 고생많으셨습니다~!!

2022-05-19 16:33 UTC, gomster96 approved these changes
수고많으셨습니다!

2022-05-19 16:44 UTC, merged