[#127]: 리뷰 생성과 인가 기능 연동
RE-BON/ReBoN pull request #165
Opened 2022-05-19 06:49 UTC by PyeongGangKim

### Description
- 리뷰 생성과 인가 기능을 연동
- header에 authorization 추가한 것과 추가하지 않은 것에 대한 인수테스트 진행
- review created response에 /api/reviews/{reviewId}로 Location 설정

### Trouble Shooting

### ETC

2022-05-19 17:02 UTC, KJunseo requested changes
고생하셨습니다!
리뷰 조금 남겼는데 확인후 다시 요청해주세요

2022-05-19 17:02 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/presentation/dto/response/MemberCreateResponse.java
> +@Setter
response에 세터를 추가하신 이유가 있나요?

2022-05-19 17:02 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/dto/request/ReviewRequest.java
> +    private List<MultipartFile> images;
저번에 리뷰 이미지는 프론트에서 s3에 저장하고 그 url만 받아오기로 하지 않았나요?? 
정리해놓은 것입니다!
https://github.com/RE-BON/ReBoN/issues/65

2022-05-19 17:02 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
ShopService에 동일한 메서드가 있는데 따로 만들어주신 이유가 있나요?

2022-05-19 17:02 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
MemberService에 동일한 메서드가 있는데 따로 만들어주신 이유가 있나요?

2022-05-19 17:02 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/AcceptanceTest.java
> +        token = extractedToken(memberResponse);
beforeEach에서 매번 로그인을 하면, 로그인이 필요하지 않은 시나리오를 테스트하고 싶을때도 회원가입이 선행될것 같은데요.
'회원가입()', '로그인요청()' 등의 공통 메서드로만 만들어놓고 필요한 테스트에 맞게 각 테스트에서 호출해서 사용하게 하는 방식은 어떤가요?

2022-05-19 17:02 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewCreateAcceptanceTest.java
> +    }
이 두 메서드도 토큰 유무만 다르고 거의 유사한 메서드라서 중복을 줄일 수 있지 않을까요?

2022-05-20 16:21 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/member/presentation/dto/response/MemberCreateResponse.java
> +@Setter
매핑할 때, 에러가 생겨서, 추가를 했었는데, 삭제를 해도 잘 작동하네요,,,수정하겠습니다,,!!

2022-05-20 16:22 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
ShopService에 private으로 구현되어 있어서, 따로 만들어 주었는데, 그 부분을 public으로 만들어도 괜찮을 까요?

2022-05-20 16:23 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
위에, method와 일관성있게 구현하고 싶어서, 따로 만들어주었습니다!! ShopService에 있는 것을 Public으로 바꾼다면, 이 부분도 고치겠습니다!

2022-05-21 05:55 UTC, gomster96 requested changes
수고많이 하셨습니다. 다른분이 잡아주신것만 고치시고, 이미지 관련 여부만 같이 결정이 되면 Approve 하겠습니다.!

2022-05-21 05:55 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
궁금합니다. 서비스 단에서 다른 서비스 단을 가지고 와도 괜찮은 것인가요? 물론 지금 생각해보니 코드의 중복을 없애기 위해 저는 좋다고 생각하긴 합니다.

2022-05-21 07:26 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/AcceptanceTest.java
> +        token = extractedToken(memberResponse);
그 방식이 좀 더 좋을 거 같네요!!

2022-05-24 03:22 UTC, KJunseo approved these changes
이만 approve하겠습니다!
추가적으로 이번 pr부분은 아니지만 ReviewService에 shop과 member 가져오는 부분에 repository에서 바로 가져오는 부분들도 service를 통해 미리 만들어진 메서드를 사용해도 좋을 것 같네요!

2022-05-24 16:58 UTC, gomster96 approved these changes
수고하셨습니다! 코드가 보고 이해하기 좋네요!

2022-05-25 12:15 UTC, merged