가게 like, unlike 구현
RE-BON/ReBoN pull request #167
Opened 2022-05-24 08:15 UTC by KJunseo

### Description
로그인 한 유저가 특정 가게 like, unlike api 구현

### Trouble Shooting

### ETC

2022-05-24 14:45 UTC, PyeongGangKim approved these changes
구현 잘 하셨네요!!
고생많으셨습니다~!!

2022-05-24 14:45 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/like/Likes.java
> +
배워갑니다~!!

2022-05-24 17:25 UTC, gomster96 requested changes
수고하셨습니다. 코드가 깔끔해서 바로바로 이해가 되었습니다. 궁금한 점 남겼습니다. 코멘트 부탁드립니다!

2022-05-24 17:25 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +
unlike 가 되었을 때 즉 좋아요를 눌렀던 것을 수정했을 때 연관관계를 끊어주셨는데, 이때 이 like 객체 자체는 어떻게 되는건가요? 

1.좋아요 -> 2.좋아요 해제 -> 3.좋아요  

위와 같은 기능이 발생했을 때, 1 번에서 생성한 like record는 남아있고, 3번에서 좋아요가 다시 생성될 거 같습니다. 사실 좋아요 같은 경우 계속 연타해서 누를 수도 있으니까?? 2번에서 삭제처리를 하는 것도 이상한데, 어떻게 남겨 두었다가 다시 연결하는 식의 방법을 고려 할 수 있을까요?

2022-05-24 17:25 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/like/Likes.java
> +
혹시 이 equals 메서드가 어디서 사용되는지 알 수 있을까요?

2022-05-25 05:05 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/like/Likes.java
> +
주소값으로 비교하지 않기 위해서 override 해준 것입니다!
unlike 과정시 equals를 재정의 하지 않으면 동일한 값을 가지고있더라도 주소값이 달라 다른객체로 취급되어 삭제를 할 수 없게 됩니다!

2022-05-25 05:12 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +
제가 잘 이해를 못했는데 추가적인 설명을 해주실 수 있을까요?

1.좋아요 -> 2.좋아요 해제 -> 3.좋아요

이 시나리오라면 1번 과정에서 like 테이블에 추가가 된 후, 2번 과정에서 like 테이블에서 record가 삭제되고 3번 과정에서 다시 생성되게 됩니다.

저는 좋아요를 연타해서 누를 순 있어도 마지막에 좋아요가 해지된 상태라면 삭제처리를 하지 않고 남겨두는게 더 어색한것 같다는 의견입니다!

2022-05-25 12:49 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +
2 좋아요 해제가 되면 like 테이블에서 레코드가 삭제 되는게 어디있나요??? 저는 해당 로직을 찾을 수 없어서 사실 여쭤봤던 겁니다!

2022-05-25 12:56 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +
orphanRemoval 옵션으로 인해 자동으로 삭제됩니다.

예전에 남겼던 리뷰 참고바랍니다.
https://github.com/RE-BON/ReBoN/pull/123#discussion_r859349681

2022-05-25 13:10 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +
아 맞네요... orphanRemoval 라 자동으로 삭제되네요 감사합니다 ! 어프로브하겠습니다.

2022-05-25 13:10 UTC, gomster96 approved these changes
수고 많이하셨습니다!

2022-05-25 13:10 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/like/Likes.java
> +
아아 이해했습니다 감사합니다!

2022-05-26 14:12 UTC, merged