[#11] : 카테고리 수정 기능 구현
RE-BON/ReBoN pull request #171
Opened 2022-05-25 18:33 UTC by gomster96

### Description
카테고리 수정 기능을 구현하였습니다. 

### ETC
코드를 구현하며, 중복 되는 부분이 발생할 것 같아서, 해당 내용을 먼저 리팩토링 하고 코드 구현을 진행하였습니다.

2022-05-26 02:30 UTC, KJunseo requested changes
고생하셨습니다!
리뷰 몇가지 남겼어요!
추가적으로 카테고리의 필드는 이름 뿐만아니라 부모 필드도 있어서 이 부분도 수정할 수 있어야 할 것 같습니다! 이 부분이 구현되어 있지 않은 것 같아요!

2022-05-26 02:30 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +        checkChildCategoryExist(category.getParent().getId(), categoryRequestDto.getName());
category.getParent().getId() 보다 그냥 category.getParent()만으로도 exists 쿼리를 실행시킬 수 있지 않나요??
조금 결이 다를 수 있지만 디미터 법칙에 위배된다고 생각합니다

2022-05-26 02:30 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +
빈이름은 안된다던지 하는 예외처리 + 테스트를 추가하면 좋을 것 같아요

2022-05-26 02:30 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/domain/repository/CategoryRepositoryCustom.java
> +}
굳이 QueryDSL을 써서 만들어주신 이유가 있나요??
spring data jpa를 사용해서 `boolean existsByParentAndName(Category category, String name);` 이런식으로 해줘도 될 것 같은데 custom을 만드신 이유가 궁금합니다!

2022-05-26 02:30 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/presentation/AdminCategoryController.java
> +    public String createCategory(@PathVariable Long id, CategoryRequest categoryRequest) {
PathVariable로 바꾼다는 게 무슨 의미인지 잘 모르겠어요!
임시로 해놓으신단 건가요..? 생성 api인데 pathvariable로 id를 가지고 있는게 어색한것 같습니다

2022-05-26 02:30 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/presentation/AdminCategoryController.java
> +
같은 메서드를 사용할 거면 네이밍을 바꿔주는게 좋을 것 같아요! 처음 읽었을 때 'update 인데 왜 createDto로 바꾸는거지?' 라는 생각이 들었어요!

2022-05-26 02:30 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/category/CategoryUpdateIntegrationTest.java
> +    public void 카테고리_수정(){
자식 카테고리를 수정 성공하는 경우도 추가하면 좋을 것 같네요

2022-05-26 02:43 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +        checkChildCategoryExist(category.getParent().getId(), categoryRequestDto.getName());
맞습니다. 제가 아직 활용이 부족했네요 감사합니다!

2022-05-26 02:44 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/domain/repository/CategoryRepositoryCustom.java
> +}
맞습니다. 제가 아직 활용이 부족했네요...! 감사합니다!

2022-05-26 02:49 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/presentation/AdminCategoryController.java
> +
네 맞습니다...! 제가 네이밍을 다 바꾸지 않았네요!

2022-05-26 02:49 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/presentation/AdminCategoryController.java
> +    public String createCategory(@PathVariable Long id, CategoryRequest categoryRequest) {
지적감사합니다. 제가 살짝 헷갈렸습니다! 감사합니다.

2022-05-26 07:21 UTC, KJunseo requested changes
리뷰 몇개 남겼어요!
다시 확인 부탁드려요!
추가적으로 코드 실행이 안되는데 이 부분도 체크바랍니다!

2022-05-26 07:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +        }
포매팅 적용이 안되어있는 것 같습니다
또 추가적으로 저는 dto에는 가능하면 로직이 들어가지 않는게 좋다고 생각해요.
데이터를 옮길때 사용하는 용도로만 쓰고 다른 비즈니스 로직은 들어가지 않는게 좋다고 생각합니다.
자식 카테고리인데 부모가 없는 경우를 검사하고 싶으신 경우에는 category를 가져오면 내부에 parent까지 가져올텐데 이를 이용하면 되지 않을까요?

만약 dto에 값이 제대로 들어왔는지를 체크하고 싶은 경우에는 @Valid 어노테이션을 찾아보시고 적용하는게 좋을 것 같아요

2022-05-26 07:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +        category.update(parentCategory, categoryUpdateRequestDto.getName());
이 작업도 굳이 parent를 가져오지 않아도 이미 category에 포함되어 있지 않나요??

2022-05-26 07:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/application/dto/request/CategoryUpdateRequestDto.java
> +import lombok.Setter;
사용하지 않는 Import 인 것 같습니다.

2022-05-26 07:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/domain/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long>{
포매팅이 적용되지 않은 것 같습니다.

2022-05-26 07:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/exception/category/CategoryIdNullException.java
> +    public CategoryIdNullException() {super("변경하려는 카테고리 id값이 입력되어야 합니다.", HttpStatus.BAD_REQUEST);}
한줄로 작성하신 이유가 있나요?

2022-05-26 08:05 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +        }
이부분은 그게 아니라, 카테고리를 수정할 때, 부모카테고리가 아닌 자식카테고리인데, 부모의 id가 들어오지 않았을때 그때 문제를 잡으려고 한 부분이라 필요했습니다..! @Valid 를 찾아보겠습니다. 감사합니다.

2022-05-26 08:09 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +        category.update(parentCategory, categoryUpdateRequestDto.getName());
이 parent는 새로운 parent이기 때문에 해당 작업이 필요합니다. 예를 들어 부모가 식당 카테고리가 있고, 그 자식카테고리가 프렌차이즈 인데, 프렌차이즈 카테고리를 수정해서 부모를 카페 카테고리로 바꾸고 싶다면, 해당 카페 카테고리를 새로운 parent로 넣어주어야하니 필요합니다!

2022-05-26 08:50 UTC, KJunseo requested changes
한 부분만 확인해주시면 approve 하겠습니다!

2022-05-26 08:50 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +
두 줄입니다!

2022-05-26 08:50 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
>          category.parent = this;
이 부분과 update에서 this.parent = parent 로직이 겹치는 것 아닌가요??

2022-05-28 08:09 UTC, PyeongGangKim requested changes
고생하셨어요!!
리뷰 남겼으니, 확인하고 다시 리뷰 부탁드려요:)

2022-05-28 08:09 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +
혹시 부모 카테고리와 이름을 동시에 변경하는 경우가 있을까요??
부모 카테고리를 변경하면, 해당 카테고리를 가지고 있는 shop들 자체가 속성이 바뀐다는 건데, 그런 경우가 있을지 궁금하네요

2022-05-28 08:09 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/exception/category/CategoryIdNullException.java
> +    }
부모 카테고리가 없을 때, 던지는 exception인 거 같은데, message에 부모 카테고리가 없다는 것을 명시해주면, 좀 더 좋을 거 같아요!

2022-05-28 08:09 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/exception/category/CategoryIdNullException.java
> +    }
부모 카테고리가 없을 때, 던지는 exception인 거 같은데, message에 부모 카테고리가 없다는 것을 명시해주면, 좀 더 좋을 거 같아요!

2022-06-06 16:19 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +
사실 거의 없을 것 같긴 합니다. 하지만 만약에 카테고리를 잘못 생성 했다면, 그것을 수정해주기 위해 기능을 할 수는 있을거 같아요!

2022-06-06 16:20 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/category/CategoryIdNullException.java
> +    }
그렇네요! Exception 을 더 명시하도록 하겠습니다.

2022-06-06 16:22 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
>          category.parent = this;
아... 맞습니다...! 제가 이것을 제대로 보지 않았네요. 너무 중요한 부분 짚어 주셔서 감사합니다.

2022-06-09 09:00 UTC, KJunseo approved these changes
이만 어푸르브 하겠습니다.
테스트 하나 안돌아가던건 머지하면 해결될까요?

2022-06-12 08:47 UTC, PyeongGangKim approved these changes
고생하셨습니다:)
준서님이 리뷰 다 해주셔서, 어푸르브 하겠습니다~

2022-06-12 08:47 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +
혹시 부모 카테고리와 이름을 동시에 변경하는 경우가 있을까요??
부모 카테고리를 변경하면, 해당 카테고리를 가지고 있는 shop들 자체가 속성이 바뀐다는 건데, 그런 경우가 있을지 궁금하네요

2022-06-25 06:04 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/domain/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long>{
감사합니다.

2022-06-25 06:04 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/category/CategoryIdNullException.java
> +    public CategoryIdNullException() {super("변경하려는 카테고리 id값이 입력되어야 합니다.", HttpStatus.BAD_REQUEST);}
고치겠습니다 확인 감사합니다.

2022-06-25 06:06 UTC, gomster96 commented
네 맞습니다! 머지하면 안돌아가는 테스트 돌아갑니다 감사합니다!

2022-06-26 07:27 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +
사실 거의 없을 것 같긴 합니다. 하지만 만약에 어떠한 Shop의 카테고리를 잘못 생성 했다면, 그것을 수정해주기 위해 기능을 할 수는 있을거 같아요!

2022-06-26 07:35 UTC, merged