[#126] Review 조회와 인가 기능 연동
RE-BON/ReBoN pull request #176
Opened 2022-05-29 06:23 UTC by PyeongGangKim

### Description
- 리뷰 조회와 인가 기능 연동

### Trouble Shooting

### ETC

2022-05-30 01:49 UTC, KJunseo requested changes
코멘트만 확인하시고 다시 요청주세요!

2022-05-30 01:49 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewReadAcceptanceTest.java
> +        Shop shop = makeTestReview(bearerToken);
로그인이 되어 있지 않은 상태인데 토큰을 얻어오는 이유가 있을까요??
로직상 토큰을 얻어오는 메서드를 로그인 메서드로 사용하시는 것 같아요 
실제 요청시는 null을 넘기긴하지만 로그인 작업이 선행되는 로직인 것 같은 느낌이 들어요

2022-05-30 01:49 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewReadAcceptanceTest.java
> +    @DisplayName("로그인이 되어 있는 상태에서 shop 리뷰를 가져올 수 있다.")
이 테스트가 돌아가지 않는 것 같습니다.
기본 생성자가 없어서 그런것같네요

2022-05-30 01:49 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewReadAcceptanceTest.java
> +    @DisplayName("로그인이 되어 있는 상태에서 내가 쓴 리뷰를 가져올 수 있다.")
이 테스트가 돌아가지 않는 것 같습니다.
기본 생성자가 없어서 그런것같네요

2022-05-30 12:03 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewReadAcceptanceTest.java
> +    @DisplayName("로그인이 되어 있는 상태에서 shop 리뷰를 가져올 수 있다.")
확인해보겠습니다!!

2022-05-30 12:03 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewReadAcceptanceTest.java
> +        Shop shop = makeTestReview(bearerToken);
준서님 말대로 굳이 로그인이 필요없는 로직인거 같네요!!

2022-05-31 03:56 UTC, KJunseo approved these changes
이만 approve 하겠습니다!

2022-05-31 15:18 UTC, gomster96 approved these changes
수고 많이 하셨습니다. approve 하겠습니다!

2022-06-01 10:27 UTC, merged