[#130] Review 삭제와 인가 기능 연동
RE-BON/ReBoN pull request #177
Opened 2022-05-29 07:29 UTC by PyeongGangKim

### Description
- 리뷰 삭제와 인가 기능 연동
- 리뷰 삭제 인수테스트 추가
- api docs 추가

### Trouble Shooting
- dev에서 lazyinitialization exception을 해결하기 전 이여서, 해당 branch를 보고 반영

### ETC

2022-05-30 01:52 UTC, KJunseo requested changes
리뷰 몇개 남겼어요! 확인하시고 다시 요청주세요!

2022-05-30 01:52 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewDeleteAcceptanceTest.java
> +        String bearerToken = getBearerToken();
로그인을 하지 않은 시나리오인데 굳이 로그인 요청이 필요한가요??

2022-05-30 01:52 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewDeleteAcceptanceTest.java
> +public class ReviewDeleteAcceptanceTest extends ReviewAcceptanceTest {
추가적으로 삭제요청은 삭제요청하는 유저와 리뷰 작성한 유저가 같은지에 대한 인수테스트도 있으면 좋을 것 같습니다.

2022-05-30 12:32 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewDeleteAcceptanceTest.java
> +        String bearerToken = getBearerToken();
로그인을 안하면, 애초에 리뷰를 보지 못하니 필요없겠네요,,,!!

2022-05-31 03:49 UTC, KJunseo approved these changes
approve 하겠습니다!

2022-05-31 15:34 UTC, gomster96 approved these changes
수고하셨습니다. 저는 딱히 지적할 부분 없었습니다!

2022-06-01 11:56 UTC, merged