[#172] : 태그 생성, 조회, 삭제 페이지 구현
RE-BON/ReBoN pull request #178
Opened 2022-06-05 13:57 UTC by leehyelim0691

### Description
태그 생성, 조회, 삭제 페이지 구현

### Trouble Shooting

### ETC

2022-06-05 16:32 UTC, KJunseo requested changes
리뷰 남긴 부분만 확인해주세요.
추가적으로 태그만의 문제는 아니라고 생각하는데, "포항"이라는 태그를 만들고 삭제 후, 새로 "포항"을 만드려고 하면 예외가 발생합니다. deleted가 true인 태그는 이미 존재하는 여부 체크를 빼야될 것 같아요

2022-06-05 16:32 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/presentation/AdminTagController.java
> +    public String createForm(Model model) {
Model을 매개변수로 받은 이유가 있나요?

2022-06-05 16:32 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/presentation/AdminTagController.java
> +        Long id = tagService.createTag(tagName);
id를 사용하지 않는데 반환받은 이유가 있나요?

2022-06-06 00:37 UTC, PyeongGangKim approved these changes
준서님이 리뷰 남긴 거에만 대답해주시면 될 거 같아요!!
고생하셨습니다:)

2022-06-06 09:47 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/presentation/AdminTagController.java
> +    public String createForm(Model model) {
앗 앞에 코드를 수정해서 바꾸었는데 반영이 되지 않은 것 같습니다! 감사합니다!

2022-06-06 09:51 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/presentation/AdminTagController.java
> +        Long id = tagService.createTag(tagName);
아 제가 실수 했네요! 감사합니다!

2022-06-07 14:04 UTC, KJunseo approved these changes
approve 하겠습니다

2022-06-08 06:59 UTC, merged