Be/review empathy/#136
RE-BON/ReBoN pull request #179
Opened 2022-06-06 16:06 UTC by gomster96

### Description
리뷰 공감, 공감 취소 API 기능 구현 

### Trouble Shooting
1. BUILDER.Default를 ArrayList(엔티티의 필드)에 할 경우 builder를 이용하지않고 생성자로 엔티티를 생성하면 해당 ArrayList  null로 초기화 됌. 따라서 Builder를 이용하여 엔티티 객체를 생성함.
2. 인수테스트에서 분명 공감 API를 실행 했는데도 Empathy 객체가 저장되지 않았던 오류 발생 -> Parent(Review)를 저장할 때 Empathy도 해주어야하는데 이를 고려하지 않았던 문제. Review의 empathies에 Cascade Persist 옵션을 추가하여 해결. 

### ETC
1. 고민 사항 
- 무엇인가 오류가 발생하여 리뷰공감 또는 공감취소 api호출을 한번에 여러번 할 수도 있는 경우가 있기 때문에  Exception으로 막아주었는데 이 과정 속에서 N+1이 발생함. 따라서 Exception으로 막아주는게 맞는지, 아니면 그냥 Client를 믿는게 맞는지 궁금함.

2. Equals 메소드를 오버라이드 할 때 private인 필드에 어떻게 접근했나 의문 해결 -> 인스턴스 Scope의 접근이 아닌, 클래스 Scope의 접근이기 때문에 가능 

관련 링크 
https://stackoverflow.com/questions/1581478/why-can-i-access-my-private-variables-of-the-other-object-directly-in-my-equa
https://stackoverflow.com/questions/21803247/comparable-class-equals-function-works-on-private-variable

2022-06-09 12:21 UTC, KJunseo requested changes
몇 가지 리뷰 남겼습니다!
확인하고 다시요청주세요

2022-06-09 12:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @PostMapping("/{reviewId}/empathize")
url에 reviews가 포함되어야하지 않을까요?

2022-06-09 12:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +            throw new ReviewEmpathyExistException();
포매팅에 맞게 한줄이어도 {}를 넣어주는게 어떤가요?

2022-06-09 12:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +            throw new ReviewEmpathyNotExistException();
여기도 {} 넣어주면 좋을 것 같습니다!

2022-06-09 12:21 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/common/admin/AdminReviewRegister.java
> +public class AdminReviewRegister {
리뷰는 관리자가 쓰는게 아닌데 api 요청으로 하지 않고 직접 서비스를 만들어서 처리하면 인수테스트의 목적과 조금 달라질 거 같다고 생각하는데, 어떻게 생각하시나요?

2022-06-09 12:21 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/common/admin/AdminMemberRegister.java
> +public class AdminMemberRegister {
회원가입도 api요청으로 처리할 수 있을것 같은데 admin으로 만드신 이유가 있나요?

2022-06-12 09:17 UTC, PyeongGangKim requested changes
고생하셨습니다!!
리뷰 남긴 거만 확인해주세요:)

2022-06-12 09:17 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/exception/review/ReviewEmpathyExistException.java
> +    }
이 부분도 테스트가 들어가면 좋을 거 같아요!!

2022-06-12 09:17 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/exception/review/ReviewEmpathyNotExistException.java
> +    }
이 부분도요!

2022-06-12 09:17 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewScore.java
> +        this.empathyCount--;
this는 제거해도 될 거 같아요!

2022-06-26 05:49 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @PostMapping("/{reviewId}/empathize")
네 맞습니다..! 제가 제대로 확인하지 않았네요 감사합니다.

2022-06-26 05:49 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +            throw new ReviewEmpathyExistException();
네 진행하겠습니다!

2022-06-26 05:52 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/review/ReviewEmpathyNotExistException.java
> +    }
해당 테스트 통합테스트에 존재합니다!

2022-06-26 05:52 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/review/ReviewEmpathyExistException.java
> +    }
해당 테스트 통합테스트에 존재합니다!

2022-06-26 05:53 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewScore.java
> +        this.empathyCount--;
네 알겠습니다..! 혹시 this를 사용하지 않는 이유가 있을까요??

2022-06-26 07:22 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/common/admin/AdminReviewRegister.java
> +public class AdminReviewRegister {
말씀하신 부분 생각하여 시도해보았는데, 현재 만들어진 ReviewCreate API의 response가 void 인 상태입니다. 하지만 리뷰를 공감하기 위해서는 ReviewID가 필요합니다. 따라서 불가피하게 만들어야 할거 같아 기존 방법을 유지하였습니다. 혹시 다른 방법이 있을까요?

2022-06-26 07:23 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/common/admin/AdminMemberRegister.java
> +public class AdminMemberRegister {
위의 내용과 동일합니다. Review를 생성해주기 위해서 처리하였습니다.

2022-06-26 09:40 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/common/admin/AdminReviewRegister.java
> +public class AdminReviewRegister {
생성 같은 경우는 응답 헤더에 Location 헤더가 있고, 이를 통해 리뷰 Id가 반환됩니다. 이를 추출해서 사용해야할듯 합니다. 인수 테스트의 경우는 실제 요청으로만 이루어져야 한다고 생각합니다!

2022-06-26 09:50 UTC, KJunseo requested changes
질문주신부분 답변 달았습니다!
확인후 요청주세요

2022-06-26 09:50 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/Member.java
> +    public void unEmpathizeReview(Empathy empathy){
포매팅 적용이 필요해보입니다.

2022-06-26 09:50 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +        if (isEmpathyExist(empathy)){
포매팅 적용이 필요해보입니다.

2022-06-26 09:50 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +        if (!isEmpathyExist(empathy)){
포매팅 적용이 필요해보입니다.

2022-06-26 09:50 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/common/admin/AdminReviewRegister.java
> +public class AdminReviewRegister {
생성 같은 경우는 응답 헤더에 Location 헤더가 있고, 이를 통해 리뷰 Id가 반환됩니다. 이를 추출해서 사용해야할듯 합니다. 인수 테스트의 경우는 실제 요청으로만 이루어져야 한다고 생각합니다!

저희 서비스는 아니지만 이 부분한번 참고해보셔도 좋을 것 같습니다.
https://github.com/KJunseo/SSG-product-information/blob/master/src/test/java/ssg/product_information/acceptance/user/UserCreateAcceptanceTest.java

2022-06-26 12:58 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/common/admin/AdminReviewRegister.java
> +public class AdminReviewRegister {
아 이렇게 추출해도 괜찮은 거군요..! 감사합니다. 저는 이렇게 빼와도 되는줄 몰랐었네요 ㅎㅎ 감사합니다!

2022-06-27 03:43 UTC, KJunseo approved these changes
이만 approve하겠습니다!

2022-06-27 03:43 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewEmpathyAcceptanceTest.java
> +        long reviewId = Long.parseLong(locations[locations.length - 1]);
location을 추출하는 작업을 매번 메서드안에서 반복하기 보다 메서드로 분리해도 좋을 것 같아요!

2022-06-27 03:46 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewEmpathyAcceptanceTest.java
> +        long reviewId = Long.parseLong(locations[locations.length - 1]);
아 메서드로 분리하는 방법이 너무 좋을 것 같습니다! 분리해서 머지하도록 하겠습니다 감사합니다!

2022-06-27 03:47 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/member/domain/Member.java
> +    public void unEmpathizeReview(Empathy empathy){
네 알겠습니다. 감사합니다!

2022-06-27 03:47 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +        if (isEmpathyExist(empathy)){
네 알겠습니다. 감사합니다!

2022-06-27 03:47 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +        if (!isEmpathyExist(empathy)){
네 알겠습니다. 감사합니다!

2022-06-27 13:04 UTC, PyeongGangKim requested changes
리뷰 남겼습니다!!
확인부탁드립니다:)

2022-06-27 13:04 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/unit/review/domain/content/ReviewScoreTest.java
> +        //given
DisplayName과 함수명이 일치하지 않는 거 같아요

2022-06-27 13:04 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewIntegrationTest.java
> +        Review review = createReview("Byungwoong", "맘스터치");
리뷰 취소 예외로 처리할 수 있는 부분 아닌가요??

2022-06-29 05:31 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/unit/review/domain/content/ReviewScoreTest.java
> +        //given
앗........ 감사합니다

2022-06-29 05:33 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewIntegrationTest.java
> +        Review review = createReview("Byungwoong", "맘스터치");
음 지금보니까 평강님 말씀이 맞습니다. 사실 그냥 공감하지 않았는데 리뷰를 취소했을 시와 같은 예외이기 때문에 중복된 테스트가 된 것 같습니다. 저는 그냥 프론트에서 실수로 fetch를 두번 보냈을 때를 잡고 싶었는데, 이게 위에꺼와 동일하다고 생각하지 못했네요! 만약에 지우라고 하시면 지우고, 둬도 괜찮다고 생각하시면 두겠습니다. 코멘트 부탁드려요 ㅎㅎ

2022-06-29 11:17 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewIntegrationTest.java
> +        Review review = createReview("Byungwoong", "맘스터치");
굳이 지워도 되지는 않을 거 같아요!!
왜 두번 하셨는지 궁금해서 리뷰했습니다!

2022-06-29 11:17 UTC, PyeongGangKim approved these changes
어푸르브하겠습니다!

2022-07-06 14:34 UTC, merged