feat[#12]: Tag 수정 기능 구현
RE-BON/ReBoN pull request #181
Opened 2022-06-13 08:03 UTC by leehyelim0691

### Description
Tag 수정 기능 구현

### Trouble Shooting

### ETC

2022-06-18 12:03 UTC, PyeongGangKim approved these changes
저는 딱히 리뷰할게 없네요!!
고생하셨습니다:)

2022-06-18 12:03 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +        this.name = name;
이 부분은 create할 때, 테스트 진행해서 안한거죠??

2022-06-20 00:28 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +        this.name = name;
create 기능 구현시 말씀하시는 건가요?! 그 부분은 TagService.java에 createTag 메소드에 구현되어 있습니다!

2022-06-20 05:58 UTC, KJunseo requested changes
코멘트 조금 남겼는데 확인하시고 답글 달아주세요!

2022-06-20 05:58 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +        validateDuplicateTag(tagName);
사용자 입장에서 동일한 이름으로 수정요청을 했을 때는 예외가 발생하지 않는 것이 좀 더 자연스럽다고 생각하는데 의견이 궁금합니다!

예를들어 '포항'이라는 태그의 이름을 '포항'이라고 바꾸려고 요청이 왔을 때는 '이미 존재하는 태그입니다' 보다는 수정이 이루어져도 되지 않나라는 생각이듭니다.

2022-06-20 05:58 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    public void update(Long id, String tagName) {
id, tagName을 dto로 묶어서 받는 건 어떤가요?

2022-06-21 06:24 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +        validateDuplicateTag(tagName);
제가 생각했을 때는 "동일한 이름으로 태그를 수정한다는 것이"

1) 이미 기존에 존재하는 **다른** 태그와 동일한 이름
    1. 영일대
    2. 양덕
    "양덕->영일대"의 상황
2) 현재 바꾸려고 하는 태그의 이름과 동일한 이름
     1. 영일대
     2. 양덕
     "양덕->양덕"의 상황

으로 나뉜다고 생각하는데,

1)은 예외를 발생하고, 2)는 예외 발생없이 똑같이 수정되도록 하는것으로 나누어서 진행하는 것을 말씀하신게 맞을까요?!

저도 이렇게 진행하는게 더 자연스러울 것 같습니다!

2022-06-21 06:24 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    public void update(Long id, String tagName) {
네! 좋은 의견 감사합니다!

2022-06-24 17:07 UTC, gomster96 reviewed
수고하셨습니다.!

2022-06-24 17:07 UTC, gomster96 approved these changes
.

2022-06-25 05:19 UTC, KJunseo requested changes
코멘트 하나 남겼는데 확인부탁드립니다

2022-06-25 05:19 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +        }
태그에서 getter로 값을 꺼내 사용하는 것 보다 메세지를 보내서 처리하는게 좋아보입니다!

2022-06-25 08:35 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +        }
좋은 의견 감사합니다! 수정해보았는데, 혹시 이렇게 진행하는 것이 맞을지 확인 부탁드립니다!

2022-06-26 09:28 UTC, KJunseo approved these changes
이만 approve 하겠습니다!

2022-06-26 14:57 UTC, merged