[#35] 리뷰 수정
RE-BON/ReBoN pull request #182
Opened 2022-06-13 13:51 UTC by PyeongGangKim

### Description
- 리뷰 수정 기능 추가
- 리뷰 수정 통합 테스트, 인수테스트 추가
- 리뷰 수정 api docs 추가

### Trouble Shooting

### ETC

2022-06-20 06:11 UTC, KJunseo requested changes
고생하셨습니다!
몇가지 코멘트 남겼는데 확인 후 다시 요청주세요

2022-06-20 06:11 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/request/ReviewUpdateRequestDto.java
> +    private List<String> imageUrls;
원래 저장되어있던 이미지 삭제 후 새로운 이미지 저장하고 url을 프론트에서 넘겨받는거죠??

2022-06-20 06:11 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @PutMapping("/reviews/{reviewId}")
리뷰 내용에 관해 대체가 되긴하지만, member, shop, 같은 부분은 대체가 되지 않아서 부분대체인 patch가 더 어울리지 않을까라는 생각이 드는데 어떻게 생각하시나요?

2022-06-20 06:11 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewScore.java
> +    }
사용되지 않는 것 같습니다.

2022-06-20 06:11 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    public void update(Member member, String content, String tip, int star) {
새로운 리뷰이미지와 관계를 맺는 부분이 빠진 것 같아요

2022-06-20 06:11 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/review/ReviewUpdateAcceptanceTest.java
> +    void reviewUpdateByEmptyReviewContent() {
별점에 관한 예외처리도 있던데 이 부분도 테스트있으면 좋을 것 같네요

2022-06-21 11:14 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @PutMapping("/reviews/{reviewId}")
그렇게 생각하니까 patch가 더 어울릴 거 같네요!!

2022-06-21 11:24 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/dto/request/ReviewUpdateRequestDto.java
> +    private List<String> imageUrls;
프론트에서 삭제한다고 가정을 했는데, 삭제하는 부분을 백엔드에서 해야될까요?

2022-06-22 07:05 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/request/ReviewUpdateRequestDto.java
> +    private List<String> imageUrls;
프론트에서 저장을 하니 프론트에서 하는게 맞는거같네요

2022-06-22 07:11 UTC, KJunseo approved these changes
고생하셨습니다!

2022-06-24 17:03 UTC, gomster96 approved these changes
수고하셨습니다!

2022-06-25 14:07 UTC, merged