[#128] 나만의 꿀팁 조회 기능
RE-BON/ReBoN pull request #186
Opened 2022-06-25 03:21 UTC by leehyelim0691

### Description
- 나만의 꿀팁 조회 기능 추가
- 나만의 꿀팁 조회 통합 테스트, 인수테스트 추가
- 나만의 꿀팁 조회 api docs 추가

### Trouble Shooting

### ETC

2022-06-25 05:51 UTC, KJunseo requested changes
몇 가지 코멘트 남겼습니다.
나만의 꿀팁 조회 기능이 정확히 어떤 기능인지를 잘 모르겠어서 pr에 조금 설명해주시면 좋을 것 같아요
<img width="972" alt="스크린샷 2022-06-25 오후 2 43 11" src="https://user-images.githubusercontent.com/45876793/175760258-5161a146-041f-4cdd-9d0e-be3d61aa3199.png">

저 네모 박스 친 부분과 관련있는 것 같은데 어떻게 화면이 보이는지를 모르겠네요. 리뷰 쓴 사람에 대한 정보와 평점도 보이는 건지 아니면 진짜 나만의 꿀팁들만 보이는건지가 좀 헷갈리네요

2022-06-25 05:51 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @GetMapping("/shops/{shopId}/tips")
주소를 보니 뭔가 shop 도메인쪽에 있어야 할 것 같은 느낌이 드는데 의견이 궁금합니다!

2022-06-25 05:51 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/ReviewDtoAssembler.java
> +                      .map(review -> tipGetByShopResponseDto(review))
메서드 참조로 바꿀 수 있을 것 같네요

2022-06-25 05:51 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/response/TipGetByShopResponseDto.java
> +}
피그마에서 나만의 꿀팁만 조회하는 부분을 찾아보려고 했는데 잘 안보여서 그런데, 가게 이름도 필요한 반환값인가요? 이미 가게 id를 가진걸로 봐서 가게에 대한 정보는 가지고 있을 것 같은데 피그마 화면을 못 찾겠어서 정확하게 모르겠네요

2022-06-25 05:51 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = reviewRepository.findAllByShop(shop, pageable).getContent();
이 부분은 페이징 처리 때문에 나눠 놓으신 건가요?

2022-06-25 05:51 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @RequiredLogin
로그인 하지 않으면 리뷰를 보지 못해서 로그인이 필요한 건가요?

2022-06-25 05:54 UTC, gomster96 requested changes
수고하셨습니다. 코맨트 확인 부탁드려요!

2022-06-25 05:54 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        System.out.println( reviewRepository.findAll(pageable).getContent());
print 찍는 부분 지워주세요 ㅎㅎ

2022-06-25 05:54 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/dto/response/TipGetByShopResponseDto.java
> +}
응답 정보가 부족한 것 같습니다. 피그마 보니까 나만의 꿀팁에 팁 날짜와 별점 정보도 필요합니다.

2022-06-25 05:54 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +                                                                                    .pageable(pageable)
포매팅 적용 필요, 혹시 빌더를 쓰신 이유가 있으실까요?

2022-06-25 05:54 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        System.out.println( reviewRepository.findAll(pageable).getContent());
아 지워진 것 확인했습니다~~

2022-06-25 08:47 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @RequiredLogin
네 맞습니다! 리뷰를 확인하는 것에 로그인이 필요하기 때문에 넣어 놓았습니다!

2022-06-25 08:53 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @GetMapping("/shops/{shopId}/tips")
좋은 의견 감사합니다! shop->review 아래에 위치하는게 좋을 것 같네요 수정하도록 하겠습니다!

2022-06-25 08:53 UTC, leehyelim0691 commented
> 몇 가지 코멘트 남겼습니다. 나만의 꿀팁 조회 기능이 정확히 어떤 기능인지를 잘 모르겠어서 pr에 조금 설명해주시면 좋을 것 같아요 <img alt="스크린샷 2022-06-25 오후 2 43 11" width="972" src="https://user-images.githubusercontent.com/45876793/175760258-5161a146-041f-4cdd-9d0e-be3d61aa3199.png">
> 
> 저 네모 박스 친 부분과 관련있는 것 같은데 어떻게 화면이 보이는지를 모르겠네요. 리뷰 쓴 사람에 대한 정보와 평점도 보이는 건지 아니면 진짜 나만의 꿀팁들만 보이는건지가 좀 헷갈리네요

2022-06-25 08:54 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/review/application/dto/response/TipGetByShopResponseDto.java
> +}
네 제가 해당 기능에 대해 착오가 있었던 것 같습니다! shopName 제외 하고 필요한 정보들을 포함하여 다시 수정하도록 하겠습니다!

2022-06-25 08:56 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = reviewRepository.findAllByShop(shop, pageable).getContent();
네 맞습니다!

2022-06-25 08:56 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        System.out.println( reviewRepository.findAll(pageable).getContent());
네 감사합니다!

2022-06-25 14:56 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/review/application/dto/response/TipGetByShopResponseDto.java
> +}
네 수정하였습니다! 감사합니다!

2022-06-25 15:03 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +                                                                                    .pageable(pageable)
shop 별로,  페이징 기능 두개를 이용해서 해당 기능을 구현해야 하다보니 가독성을 높이기 위해 builder를 이용했습니다!

2022-06-25 15:18 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/review/application/dto/ReviewDtoAssembler.java
> +                      .map(review -> tipGetByShopResponseDto(review))
혹시 어떤 메소드 참조를 이야기 하시는 걸까요?! 잘 모르겠습니다ㅠ!

2022-06-26 09:37 UTC, KJunseo requested changes
코멘트 남긴 것 확인바랍니다!

2022-06-26 09:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/ReviewDtoAssembler.java
> +                      .map(review -> tipGetByShopResponseDto(review))
```suggestion
                      .map(ReviewDtoAssembler::tipGetByShopResponseDto)
```

2022-06-26 09:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/response/TipGetByShopResponseDto.java
> +}
사실 이렇게 반환을 하면 가게의 모든 리뷰 반환 기능과 뭐가 다른지를 모르겠어요. 피그마에서 해당 기능이 누락된 걸까요? 

나만의 꿀팁이 없는 리뷰는 반환하지 않는다고 해도 그렇다면 해당 기능은 기존의 리뷰 조회 기능에 추가되어야하는 기능이지 이 기능이 나만의 꿀팁 조회 기능이 맞는지를 모르겠어요

2022-06-26 09:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @GetMapping("/shops/{shopId}/review/tips")
reviews로 복수형 쓰는건 어떻게 생각하시나요?

2022-06-30 03:49 UTC, closed without merging