Hotfix/be/review update error
RE-BON/ReBoN pull request #194
Opened 2022-06-26 14:34 UTC by PyeongGangKim

### Description
- review update integration null point exception 에러 해결

### Trouble Shooting

### ETC

2022-06-26 14:55 UTC, gomster96 approved these changes
수고하셨습니다!

2022-06-27 03:48 UTC, KJunseo requested changes
제 의견을 남겨봤는데 확인후 요청주세요!

2022-06-27 03:48 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        }
여기서 null 체크보다는 dto 변환시 빈 리스트를 할당해주는 식으로 한 후 처리하는건 어떤가요?

2022-06-27 03:48 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        }
위와 동일한 의견입니다!

2022-06-27 03:48 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +        }
여기도 동일한 의견입니다!

2022-06-27 03:50 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        }
우와 이렇게 처리하는 방법이 더 안전하겠네요!

2022-06-27 08:38 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        }
그게 좋겠네요!!

2022-06-27 12:46 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        }
controller에서 dto를 받았을 때, 빈 list를 할당해주는 것으로 구현되어 있어, 실제 구동할 때는 문제가 없을 것으로 보여, test에만 빈 list를 넣어주었습니다.

2022-06-28 06:50 UTC, KJunseo requested changes
한 가지만 확인부탁드립니다!

2022-06-28 06:50 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        }
이 부분도 도메인안에서 처리하거나 할 수 있지 않을까요?

2022-06-28 11:35 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        }
아 제가 이건 확인 못했군요,,,

2022-06-29 05:38 UTC, KJunseo approved these changes
어푸르브 하겠습니다!

2022-06-29 11:11 UTC, merged