[#140] 내 정보 조회 기능
RE-BON/ReBoN pull request #195
Opened 2022-06-26 14:40 UTC by leehyelim0691

### Description
- 내 정보 조회 기능 구현

### Trouble Shooting

### ETC

2022-06-26 15:21 UTC, gomster96 requested changes
커맨트 확인 부탁드립니다. 그리고 Member의 경우만 MemberController 로 존재하네요. 저희 여기 부분도 통일해야할지 상의해봐야할거같아요..!

2022-06-26 15:21 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/member/application/MemberService.java
> +        Member member = findById(id);
네이밍을 findMemberInfo 로 하는건 어떨까요?? 저는 findByMemberId하면 뭔가 어색한 느낌이 들었습니다.

2022-06-26 15:21 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberReadAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
여기에 status 코드만 넣지말고, 받아온 유저의 이메일이나 닉네임도 예상하는 값이랑 일치하는지 테스트가 있으면 좋을 것 같습니다.

2022-06-27 04:00 UTC, KJunseo requested changes
몇 가지 코멘트 남겼습니다!
확인 후 요청주세요

2022-06-27 04:00 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/presentation/MemberController.java
> +    public ResponseEntity<MemberReadResponse> getMemberInfo(@PathVariable Long memberId) {
로그인 되어 있다면 @Login 으로 argument로 받는건 어떤가요? 굳이 주소창에 member id를 노출시킬 필요가 없어 보여요

2022-06-27 04:00 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberReadAcceptanceTest.java
> +        LoginMember loginMember = authService.findMemberByToken(token);
서비스를 직접 호출하는 것이 인수테스트 목적과 맞지 않는다고 생각해요.
token을 함께 보내 token에서 추출하는게 좋아보입니다. 

아래 테스트도 동일합니다!

2022-06-27 04:00 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberReadAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
동의합니다

2022-06-28 10:44 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/member/application/MemberService.java
> +        Member member = findById(id);
좋은 의견 입니다!!

2022-06-28 11:01 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberReadAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
좋은 의견 감사합니다!

2022-06-28 11:03 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/member/presentation/MemberController.java
> +    public ResponseEntity<MemberReadResponse> getMemberInfo(@PathVariable Long memberId) {
좋은 의견 감사합니다!

2022-06-28 11:20 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberReadAcceptanceTest.java
> +        LoginMember loginMember = authService.findMemberByToken(token);
좋은 의견 감사합니다!

2022-06-29 05:32 UTC, KJunseo approved these changes
이만 어푸르브 하겠습니다!

2022-07-01 04:34 UTC, gomster96 approved these changes
수고하셨습니다. 어프로브 하겠습니다.

2022-07-03 16:40 UTC, merged