[#137] : 내가 찜한 가게 리스트 받아오기 API 구현
RE-BON/ReBoN pull request #196
Opened 2022-06-26 14:57 UTC by gomster96

### Description

내가 찜한 가게 리스트 받아오기 API 구현

### Trouble Shooting

### ETC
- Review 쪽 Test 에러 부분 제외하고, 나머지 테스트 다 진행됩니다.

2022-06-27 04:08 UTC, KJunseo requested changes
코멘트 남긴 것 확인 후 다시 요청 바랍니다!

2022-06-27 04:08 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/presentation/ApiShopController.java
> +    public ResponseEntity<List<LikeShopResponse>> getLikeShops(@Login LoginMember loginMember) {
피그마를 보니 카테고리별로 나눠져있던데, 요청 받을 때 카테고리도 받아서 해당 카테고리에 맞는 가게 리스트만 반환해야하지 않을까요?

2022-06-27 04:08 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +        List<Likes> likes = likesRepository.findByMember(member);
member 내부에 likes가 존재하는데 따로 repository로 호출하신 이유가 있나요?

2022-06-27 04:08 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +    public List<LikeShopResponseDto> findLikeShops(Long memberId) {
@Transaction(reaonly)를 붙여주는게 좋을 것 같네요

2022-06-27 04:13 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +    public List<LikeShopResponseDto> findLikeShops(Long memberId) {
아 네 맞습니다. 붙여주는게 좋을 것 같습니다. 감사합니다!

2022-06-27 04:17 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/presentation/ApiShopController.java
> +    public ResponseEntity<List<LikeShopResponse>> getLikeShops(@Login LoginMember loginMember) {
아 근데 내가 찜한 리스트에 경우, 사용자가 해당 페이지를 사용하고 있는 동안에는, 찜하기에 대한 기록 내역이 변하지 않기 때문에 카테고리 별로 받는게 더 비효율적이라고 생각했습니다.
 Response에 categoryId와 categoryName을 주었기 때문에 이에 따라 프론트에서 전체 데이터를 가지고 있고, 탭을 누를 때마다 프론트에서 카타고리에 따른 분류를 해서 처리하는게 효율적일 것이라고 판단하여 이렇게 개발했습니다. 

혹시 해당의견에 어떻게 생각하시는지 코멘트 남겨주실 수 있을까요?

2022-06-27 04:20 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +        List<Likes> likes = likesRepository.findByMember(member);
한번에 호출로 shop에 대한 정보들을 받을 수 있기에 더 효율적이라고 생각하여 이렇게 개발하였습니다. member안의 likes를 사용하면 member.getLikes().forEach() ~~ 이런 식으로 접근 할 수 있는데 이것보다는 더 깔끔하게 보여서 이렇게 생각했습니다. 음.... 준서님께서는 어떻게 생각하시나요??

2022-06-27 04:27 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +        List<Likes> likes = likesRepository.findByMember(member);
이 부분은 객체 지향적인 측면에서 보면 조금 어색하다고 생각이 들어요.
member객체에게 좋아하는 가게 가져와 라고 메세지만 보내는 식이 더 자연스럽다고 생각해요

2022-06-27 04:30 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/presentation/ApiShopController.java
> +    public ResponseEntity<List<LikeShopResponse>> getLikeShops(@Login LoginMember loginMember) {
개인적으로는 사실 메인 페이지 조회와 크게 다르지 않은 기능이라고 생각이 들어요. 
추가적으로 페이징 기능도 필요하다고 생각이 들어서 모든 가게리스트를 받아서 프론트에서 카테고리별로 분류 후 페이징 처리를 하면 원하는 데이터를 얻기 힘들 것 같고, 모든 리스트를 메모리에 올려서 반환해야하므로 이게 더 비효율적이지 않을까? 라는 생각이 듭니다! 다른 분들 의견도 궁금하네요

2022-06-27 04:38 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +        List<Likes> likes = likesRepository.findByMember(member);
아 객체 지향적으로 고려해야 했군요! 감사합니다. 해당 부분 반영하여 수정하겠습니다.

2022-06-27 13:45 UTC, PyeongGangKim requested changes
리뷰 남겼습니다
저 부분만 얘기해보면 될 거 같아요:)

2022-06-27 13:45 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/presentation/ApiShopController.java
> +    public ResponseEntity<List<LikeShopResponse>> getLikeShops(@Login LoginMember loginMember) {
저도 메인 페이지와 비슷한 플로우라고 생각이 들어, 메인 페이지와 동일한 플로우로 구현하는 것이 좋을 거 같다고 생각이 들어요!!
페이징 부분을 생각을 한다면, 카테고리 별로, 받는 게 좀 더 나을 거 같다는 생각이 듭니다

2022-06-30 06:21 UTC, KJunseo requested changes
확인 후 다시 요청부탁드립니다!

2022-06-30 06:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +                     .filter(like -> like.getShop().sameCategory(category))
getShop을 통해 꺼내오는게 아니라 메세지를 보내는건 어떤가요?

2022-06-30 06:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +        return member.getLikes().stream()
이 부분도 getLikes()를 통해 꺼내기 보다 메세지를 보내도 괜찮지 않을까요?

2022-07-29 13:15 UTC, KJunseo requested changes
새로 변경하신 부분에만 리뷰남겼습니다!
한 가지 리뷰 남긴것만 확인해주세요!

2022-07-29 13:15 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +
페이징처리를 직접해주신 이유가 있나요??
이 경우는 메모리에 모든 결과를 올리고 나서 따로 페이징 처리를 해주게되어 메모리 측면에서 좋지 않을 것 같은 생각이들어서 생각이 궁금합니다!

2022-07-31 05:52 UTC, PyeongGangKim requested changes
직접 페이징 처리하는 부분만 pageable로 jpa로 처리하면 될 거 같아요!!

2022-08-13 14:50 UTC, KJunseo approved these changes
고생하셨슴다 어푸르브할게요

2022-08-26 14:10 UTC, PyeongGangKim approved these changes
어푸르브 할게요!

2022-08-29 06:24 UTC, merged