[#141]: 내 정보 수정 기능 구현
RE-BON/ReBoN pull request #197
Opened 2022-06-26 17:55 UTC by leehyelim0691

### Description
- 내 정보 수정 기능 추가
-
### Trouble Shooting

### ETC

2022-06-27 04:16 UTC, KJunseo requested changes
코멘트 확인 후 다시 요청주세요!

2022-06-27 04:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/presentation/MemberController.java
> +            @PathVariable Long memberId,
url에 memberId를 노출하지 않고, @Login을 이용하여 토큰을 통해 추출하는게 좋아보입니다!

2022-06-27 04:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/application/MemberService.java
> +        member.update(memberUpdateRequestDto.getNickname(), memberUpdateRequestDto.isAgreed());
중복 닉네임 체크 과정이 필요하지 않을까요?

2022-06-27 04:16 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberUpdateAcceptanceTest.java
> +    }
이 부분이 memberCreateAcceptanceTest와 겹치는 것 같은데 따로 두신 이유가 있나요?

2022-06-27 04:16 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberUpdateAcceptanceTest.java
> +        LoginMember loginMember = authService.findMemberByToken(token);
서비스를 직접 호출하는 건 인수테스트와 부합하지 않는 것 같습니다!
가지고 있는 토큰을 이용해서 요청을 보낼 수 있을 것 같아요.
아래 테스트도 동일합니다.

2022-06-28 11:41 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/member/presentation/MemberController.java
> +            @PathVariable Long memberId,
좋은 의견 감사합니다!

2022-06-28 11:41 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/member/application/MemberService.java
> +        member.update(memberUpdateRequestDto.getNickname(), memberUpdateRequestDto.isAgreed());
앗 맞네요! 감사합니다!

2022-06-28 11:41 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberUpdateAcceptanceTest.java
> +    }
실수로 들어간 것 같습니다! 감사합니다!

2022-06-28 11:42 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberUpdateAcceptanceTest.java
> +        LoginMember loginMember = authService.findMemberByToken(token);
좋은 의견 감사합니다!

2022-06-29 05:36 UTC, KJunseo requested changes
리뷰 확인 후 다시 요청주세요!

2022-06-29 05:36 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/application/MemberService.java
> +        member.update(memberUpdateRequestDto.getNickname(), memberUpdateRequestDto.isAgreed());
중복 닉네임 체크가 아직 없는 것 같아요!!

2022-06-29 05:36 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberUpdateAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
값이 제대로 수정되었는지도 확인하면 좋을 것 같아요

2022-06-29 07:08 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/member/application/MemberService.java
> +        member.update(memberUpdateRequestDto.getNickname(), memberUpdateRequestDto.isAgreed());
앗 까먹었네요 감사합니다!

2022-06-29 07:08 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/acceptance/member/MemberUpdateAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
감사합니다!

2022-06-30 06:16 UTC, KJunseo approved these changes
이만 어푸르브 하겠습니다!

2022-07-01 04:45 UTC, gomster96 approved these changes
수고하셨습니다!

2022-07-03 16:32 UTC, merged