[#148] 관리자 리뷰 조회 페이지
RE-BON/ReBoN pull request #198
Opened 2022-06-27 12:35 UTC by PyeongGangKim

### Description
- 관리자 리뷰 조회 페이지
- search api 적용하여, 원하는 내용 검색

### Trouble Shooting
- 'tagRepository'를 registerd 못한다는 에러 -> application.yml에 spring.main.allow-bean-definition-overriding: true 추가해서 해결

### ETC

2022-06-28 06:54 UTC, KJunseo requested changes
한 가지만 답변 부탁드립니다!

2022-06-28 06:54 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/config/WebConfig.java
> +        registry.addInterceptor(loginInterceptor).addPathPatterns("/api/**");
이 부분 추가해주신 이유가 있을까요?? 궁금해서 코멘트 남깁니다!

2022-06-28 11:40 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/config/WebConfig.java
> +        registry.addInterceptor(loginInterceptor).addPathPatterns("/api/**");
이 부분을 추가하지 않으면 부트스트랩이 연결이 안되서 추가하였습니다!

2022-06-29 05:39 UTC, KJunseo approved these changes
이만 어푸르브하겠습니다!

2022-06-29 11:38 UTC, gomster96 approved these changes
수고하셨습니다!

2022-06-29 11:38 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/config/WebConfig.java
> +        registry.addInterceptor(loginInterceptor).addPathPatterns("/api/**");
아 이렇게해야 부트스트랩이 연결이 되는군요...! 저도 반영하겠습니다.

2022-06-29 12:48 UTC, merged