[#125] : 로깅 기능 구현
RE-BON/ReBoN pull request #258
Opened 2022-07-19 05:57 UTC by gomster96

### Description
prod 모드일때는 AWS Cloud Watch로, prod모드가 아닐 때는 console로 로그가 나오도록 구현하였습니다. 또한 request와 response의 payload들을 출력해주기 위해 Filter를 사용했습니다.

### Trouble Shooting
- AWS Cloud Watch에 로그를 남기기 위해선 CloudWatchLogsFullAcess 권한이 필요합니다.
- logback의 버전이 1.6일 경우에는 logback의 xml파일에 accessKey, SecretAcessKey를 추가해야합니다.

### ETC

2022-07-29 10:29 UTC, KJunseo requested changes
리뷰가 많이 늦어져 죄송합니다!
몇 가지 의견과 궁금한 점 남겼는데 답변 주시면 감사하겠습니다!

추가적으로 어떤 과정을 거치는지 조금 자세하게 설명해주실 수 있을까요?
prod인 경우와 prod 아닌 경우를 나눠서 하신 것 같은데 궁금한 점이 있어 요청드립니다!!
- 어떤 로그들을 남겼고(ex. error log, application log(스프링 로컬에서 실행시 보여지는 스프링 로그), request log..)
- aop, intercepter도 있는데 filter를 사용한 이유
- 어떤 형식으로 저장하는지?(파일에 날짜별로 저장, 용량이 차면 어떻게 되는지 등)




추가적으로 직접 실행해보려했으나 아래와 같은 에러가 발생해서 실행이 안되네요. 서브 모듈에 있는 appender 파일을 복사해주는 작업을 build.gradle에서 해주지 않아 발생하는 문제라고 추측은 되는데 정확하게는 모르겠습니다!
<img width="1325" alt="스크린샷 2022-07-29 오후 7 27 14" src="https://user-images.githubusercontent.com/45876793/181740389-f9a48cdb-1353-4094-80ec-2577da555674.png">

2022-07-29 10:29 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/exception/GlobalExceptionHandler.java
> +
private static final로 설정해주는 건 어떤가요? 전역으로 하나의 인스턴스만 사용해도 될 것 같다는 생각이 들어서요!

추가적으로 `public static Logger getLogger(Class<?> clazz)`를 쓰는 이유는 어떤 클래스에서 에러를 남겼는지도 확인하기 위해서라고 생각하는데 RebonApplication 클래스로 넘겨주면 어디서 발생했는지 헷갈릴 거 같아요 GlobalExceptionHandler.class를 넘겨서 controllerAdvice에서 예외가 잡혔구나 라는걸 알 수 있게 하는것도 좋을 거 같아요

2022-07-29 10:29 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/exception/GlobalExceptionHandler.java
>          return ResponseEntity
이 부분은 에러 로그를 남기지 않은 이유가 있나요?

2022-07-29 10:29 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/exception/GlobalExceptionHandler.java
>                               .body(new ExceptionResponse(e.getMessage()));
이 부분도 에러 로그를 남기지 않은 이유가 있나요?

2022-07-29 10:29 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/exception/GlobalExceptionHandler.java
> +    }
ResponseStatus와 ResponseEntity 둘 다 사용하신 이유가 있나요? 또 RebonException을 잡는 메서드에서 Bad request 처리를 한다고 생각하는데 서버관련에러를 500대가 아닌 bad request로 변환해주시는 이유가 궁금합니다!

2022-07-29 10:29 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/filters/LoggingFilter.java
> +        MDC.put("traceId", UUID.randomUUID().toString());
이 MDC는 무슨 역할인가요??

2022-07-31 04:25 UTC, PyeongGangKim approved these changes
메서드 분리도 잘 되어있고, 처음하시는 거라 어려웠을 텐데 고생많으셨습니다!!

준서님이 리뷰 주신것만 반영하면 될 거 같습니다!!

2022-08-14 14:57 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/GlobalExceptionHandler.java
> +
오 넘겨주는 Class의 이름만으로도, 이렇게 알 수 있게 하는 방법이 있네요. 감사합니다.

2022-08-23 11:25 UTC, gomster96 commented
리뷰에 대한 반영이 많이 늦어져서 죄송합니다. 

1. 남기는 로그 
먼저 남기는 로그들은 크게 두 레벨(error, info)로 나누었습니다. info에 경우 application log, request, response, client error(400번대) 등이 있고, error는 server error(500번대)와 그외 저희가 지정해두지 않은 Exception이 발생할 경우 에러로그를 남기도록 하였습니다. 

2. Filter 로 구현한 이유
저는 HTTP 요청 로그를 남기려고 하는데, Spring Context에 들어가기 전에 오류가 발생한다면, 이때는 HTTP 로그를 남기지 못하기 때문에 Filter로 구현하는 방법을 찾아봤습니다. 

3. 어떤 형식으로 저장하는지? 
현재는 AWS Cloud Watch 에 저장하기 때문에, 기본적으로 로그들이 영구저장되는 것으로 알고 있습니다. 

좋은 리뷰 감사합니다.

2022-08-23 13:07 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/GlobalExceptionHandler.java
>          return ResponseEntity
앗... 남겨야 한다고 생각합니다. 감사합니다.

2022-08-23 13:07 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/GlobalExceptionHandler.java
>                               .body(new ExceptionResponse(e.getMessage()));
남겨야 한다고 생각합니다. 감사합니다.

2022-08-24 11:05 UTC, KJunseo approved these changes
이만 어푸르브하겠습니다. 고생많으셨습니다.
제가 저번 리뷰에 남긴 MDC 부분에 대한 설명만 부탁드립니다! 추가적으로 사용하지 않는 import들이 있는 것 같아서 그 부분도 포매팅 적용해주시면 좋을 것 같습니다.

2022-08-26 12:14 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/filters/LoggingFilter.java
> +        MDC.put("traceId", UUID.randomUUID().toString());
MDC 는 멀티쓰레드 환경에서, 실행되는 task는 로그가 섞여 있을 수 있기 때문에, 각 쓰레드마다 MDC를 통해 ThreadLocal 변수에 Id값을 할당하여 실행흐름을 트래킹하도록 하는 것입니다. ...  저희 웹은 멀티쓰레드에서 돌아가지 않기 때문에 결국 의미있는 값이 되지는 않겠네요...

2022-08-26 12:14 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/GlobalExceptionHandler.java
> +    }
아....! 이때는 저희가 의도하지 않은 에러이므로 500번대 에러가 맞습니다. 좋은 지적 감사합니다.

2022-08-29 06:23 UTC, merged