[#138] : 회원 탈퇴 API 구현
RE-BON/ReBoN pull request #271
Opened 2022-08-23 12:33 UTC by gomster96

### Description
로그인 할 때 회원 관련해서 찾는 것은 email 기준으로 하기 때문에 회원 탈퇴 시에 회원 Profile의 email과 nickName을 탈퇴한 유저의 것으로 하였습니다. 이렇게 하면 이전 탈퇴 전의 활동 내역들은 유지하면서, 가입되었던 회원은 더 이상 활동을 하지 못하게 될 것이라고 생각했습니다. 

### Trouble Shooting

### ETC

2022-08-24 11:10 UTC, KJunseo requested changes
한 가지 질문 남기고 확인해주시면 어푸르브 하겠습니다.

현재 이 로직대로라면 회원 탈퇴를 하고 나서는 일정기간 내 자기 정보 복구는 불가능한건가요? 탈퇴라는 유저 상태값을 둘 수도 있었을텐데 이 방법을 사용하신 이유가 궁금합니다!

2022-08-24 11:10 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/Member.java
> +    public String getImage() {return profile.getImage();}
공백으로 나누는게 가독성 면에서 나아보입니다.

2022-08-26 14:14 UTC, PyeongGangKim approved these changes
고생하셨습니다 어푸르브 하겠습니다!

2022-08-26 14:14 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/member/domain/Profile.java
> +        email = "withdrawer";
닉네임을 withdrawer로는 설정 못하겠네요ㅋㅋ

2022-08-30 13:07 UTC, KJunseo approved these changes
어푸르브 합니다

2022-08-30 13:07 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/member/domain/Member.java
> +    public String getImage() {return profile.getImage();}
네 감사합니다!

2022-08-30 13:46 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/member/domain/Profile.java
> +        email = "withdrawer";
흠 anonymous 로 하도록 하겠습니다!

2022-08-30 13:50 UTC, merged