feat[#17]: admin review add 기능 추가
RE-BON/ReBoN pull request #47
Opened 2022-03-17 04:04 UTC by PyeongGangKim

### Description
- admin페이지 review add
- admin페이지에서는 review test용으로 생성하는 것이기 때문에, review title, content, tip만 입력받도록 했음.

### Trouble Shooting

### ETC
- DTO에는 setter추가

2022-03-17 05:18 UTC, KJunseo requested changes
제 의견을 적어봤는데 모두 반영하실 필요는 없고 의견을 적어주시면 감사하겠습니다! 다시 리뷰 요청 주세요!

+) 일반 사용자용 리뷰 생성 기능을 구현하시는 건 줄 알았는데 테스트 용 기능인 줄 몰랐습니다 ㅠㅠ 아래에 관련 코멘트 남겨놨어요.

2022-03-17 05:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    public Long adminReviewCreate(AdminReviewPostRequestDto adminReviewPostRequestDto) {
이 메서드는 나중에 일반 사용자가 리뷰를 생성할 때 쓰일 수 있는 메서드인가요?
그렇다면 네이밍을 좀 더 일반적으로 바꾸는 게 좋을 것 같아요.

조금 결이 다를 수 있지만 테스트 용으로만 사용되는 메서드라면 저는 테스트만을 위한 코드가 프로덕션 코드에 존재하는 것은 좋지 않다고 생각해요. 
- 프로덕션 코드와 테스트 코드가 한 클래스에 존재하게 되어 복잡도 증가
- 테스트를 위한 코드가 실 서비스에도 배포
- 결국 수동 테스트를 위한 메서드

리뷰 목록을 관리하기 위해 생성하는 용도라면 조회 기능을 구현하고 테스트 코드를 통해 임의로 Reivew 객체를 생성해서 테스트 하는 것이 더 좋을 것 같아요.

2022-03-17 05:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    private ReviewContent createReviewContent(AdminReviewPostRequestDto adminReviewPostRequestDto) {
서비스에 메서드가 많아지면 조금 복잡해 질 것 같아서 Dto를 도메인으로 바꾸는 로직은 개인적으로 Dto 안에서 처리해도 될 것 같아요.

2022-03-17 05:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +    }
지금은 각 생성자에서 할당 작업이 일어나고 있는 것 같은데요. 생성자를 여러개 둘 것이면 초기화 로직은 하나의 주생성자에서만 처리하고 부 생성자들이 주생성자를 호출하는 방법은 어떤가요?

```suggestion
    public ReviewContent(String title, String content) {
        this(title, content, "");
    }

    public ReviewContent(String title, String content, String tip) {
        IsNotValidtitleAndContent(title, content);
        this.title = title;
        this.content = content;
        this.tip = tip;
    }
```

2022-03-17 05:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +    }
이 두 메서드가 완전히 똑같은 코드인 것 같은데 분리해놓은 이유가 있으신가요?

2022-03-17 05:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +    private void IsNotValidtitleAndContent(String title, String content) throws ReviewTitleFormatException, ReviewContentFormatException {
혹시 throws를 추가해주신 이유가 있을까요?
CheckException인 경우는 반드시 throws를 추가해주지만 UncheckedException 같은 경우 붙여주지 않는 걸 권장한다고 알고 있어요

2022-03-17 05:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/AdminReviewController.java
> +@Slf4j
테스트 용으로 찍어보기 위해 두신 건가요?

2022-03-17 05:18 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/review/domain/content/ReviewContentTest.java
> +                .build())
ReviewContent 생성에 관한 테스트인 것 같은데, `Review.builder()` 부분이 필요한가요??

또 null이거나 공백만 있는 문자열도 검사하려고 하시는 것 같은데 빠져있는 것 같아요. @NullSource 등을 추가해주면 좋을 것 같네요

2022-03-17 05:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        return review.getId();
오 이렇게 안해줘도 자동으로 id가 들어가나요?? 몰랐네요

```suggestion
        Review saved = reviewRepository.save(review);
        return saved.getId();
```

2022-03-17 05:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/AdminReviewController.java
> +import com.handong.rebon.review.domain.Review;
사용하지 않고 있는 것 같아요

2022-03-17 14:26 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +    }
저는 생성자 위에 @Builder 를 추가하여 public ReviewContent(String title, String content, String tip) 이거 하나로 생성자를 줄일 수 있었습니다.

2022-03-20 06:16 UTC, KJunseo requested changes
고생하셨슴다. 확인하고 다시 요청주세요!

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/request/ReviewCreateRequestDto.java
> +    private int likeCount;
새로운 리뷰 생성시 공감 수까지 입력으로 들어올까요?

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +    }
```suggestion
public class ReviewContent {
    private String title;
    private String content;
    private String tip;

    public ReviewContent(String title, String content) {
        this(title, content, "");
    }
```

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +        isNotValidTitleAndContent(title, content);
isNotValidTitleAndContent 메서드 호출 이후에 isNotValidData 메서드가 호출되고 있어서 두 메서드의 순서를 바꾸는 게 좀 더 가독성이 좋을 것 같아요

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +        isNotValidTitleAndContent(title, content);
추가적으로 메서드 명만 보면 '제목과 내용이 올바르지 않다'고만 느껴져서 '제목과 내용을 검증한다'라는 느낌이 들면 더 좋을 것 같기도하네요

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewScore.java
> +    private int likeCount; // empathyCount로 바꾸는 건 어떨까?
empathyCount 괜찮은 것 같아요!

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
>      private List<Empathy> empathies;
```suggestion
    @OneToMany(mappedBy = "review")
    private List<Empathy> empathies = new ArrayList<>();
```

컬렉션의 경우 null문제가 일어날 수 있어서 필드에서 바로 초기화해주는 것이 좋다고 합니다.
https://velog.io/@yebali/Spring-JPA-Entity%EC%84%A4%EA%B3%84-%EC%8B%9C-%EC%A3%BC%EC%9D%98%EC%A0%90

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewImages.java
>  public class ReviewImages {
내부 필드에 cascade 옵션을 줘도 될 거 같아요
ReviewImage같은 경우는 Review에 확실히 속한다고 볼 수 있다고 생각해요. Review 생성시 각 ReviewImage들에게도 Review 연관 관계를 할당해주면 좋을 것 같네요

실행시켜보면 연관관계가 제대로 들어가지 않네요
<img width="212" alt="스크린샷 2022-03-20 오후 3 15 24" src="https://user-images.githubusercontent.com/45876793/159150632-3725f155-e9f7-411a-8d6c-525ff53de79f.png">

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    }
이 메서드들은 테스트에서 사용하기 위해 만들어놓은 것 같아요. 나중에 실제로 프로덕션 코드에서 필요하게 될 때 추가해줘도 되지 않을까요?

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewScore.java
> +        }
별점을 몇점까지로 정하진 않았지만 최대 평점을 넘어가는지도 확인해야하지 않을까요?

2022-03-20 06:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/AdminReviewController.java
> +public class AdminReviewController {
생성기능은 admin 기능이 아닌 것 같아요! API니까 RestController도 생성하면 좋을 것 같네요

2022-03-20 06:16 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/review/domain/content/ReviewContentTest.java
> +        assertThatThrownBy(() ->new ReviewContent(title, "너무 좋아요"))
```suggestion
        //given
        //when, then
        assertThatThrownBy(() -> new ReviewContent(title, "너무 좋아요"))
```
화살표와 new 사이 띄워주면 좋을 것 같네요

2022-03-20 06:16 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/review/domain/content/ReviewScoreTest.java
> +    public void reviewStarNegativeException() {
최대 평점을 넘어가는 부분도 테스트하면 좋을거같네요

2022-03-21 08:57 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/request/ReviewCreateRequestDto.java
> +    private int likeCount;
제가 잘못 생각했나보네요!!

2022-03-21 09:06 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
>      private List<Empathy> empathies;
감사합니다!

2022-03-21 09:27 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    }
그렇게 하는게 낳을거 같네요!!

2022-03-21 13:15 UTC, gomster96 approved these changes
많이 배웠습니다. 코맨트 남겼으니 관련해서 답 해주세요 ㅎ

2022-03-21 13:15 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/review/application/ReviewServiceTest.java
> +        assertThat(review.getShopName()).isEqualTo(shop.getShopContent().getName());
assertThat이 모든 부분에 다 있는데, 물론 필요해보이긴 합니다. 근데 assertThat을 뭔가 줄일 수 있는 방법은 없을까요? (그냥 궁금한겁니다 ㅋㅋ)

2022-03-21 13:15 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopScore.java
> +@NoArgsConstructor
기본생성자에 @NoArgsConstructor(acess = AccessLevel.PROTECTED)를 해주면 protected로 인해 좀 더 무분별한 객체 생성을 막을 수 있답니다!

2022-03-21 13:15 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        return new ReviewImages(Arrays.asList(url1, url2));
오 이렇게 Array로 저장하는 방법 좋네요 배웠습니다 👍

2022-03-21 13:17 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopScore.java
> +@NoArgsConstructor
넵 감사합니다!!

2022-03-22 05:22 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopScore.java
> +@NoArgsConstructor
엔티티가 아닌 경우에도 protected로 해줘야 하나요??

2022-03-22 05:25 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/review/application/ReviewServiceTest.java
> +        assertThat(review.getShopName()).isEqualTo(shop.getShopContent().getName());
찾아보니까 없는 거 같네요,,, 이거와는 다른 얘기지만, assertAll를 사용하면, 중간에 하나의 assertThat이 터져도, 나머지도 검증이 가능합니다!

2022-03-22 09:52 UTC, gomster96 requested changes
수고많으셨씁니다 ㅎㅎ 커맨트에 답 남겨주십쇼

2022-03-22 09:52 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    }
저도 이부분을 리뷰받았었는데, getReviewImages()를 하는것 보단 이 기능을 reviewImages에서 할 수 있도록 메서드를 만드는게 좋을 것 같습니다.

2022-03-22 09:57 UTC, KJunseo requested changes
고생하셨습니다! 몇 가지 궁금한 부분들이 있어 리뷰 남겼어요 확인해보시고 다시 요청주세요!

2022-03-22 09:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    public ReviewResponseDto create(ReviewCreateRequestDto reviewCreateRequestDto) {
보통 자원 생성시 생성 후 생성된 리소스의 id를 반환하는 것으로 알고 있는데 혹시 이렇게 모든 정보를 넘겨주신 이유가 있을까요?

```
// ex
201 created 
Location: /reviews/3
```

2022-03-22 09:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    }
reviewImages에서 List를 꺼내서 처리하기보다는 reviewImages에 메세지를 보내는식으로 처리하는 건 어떨까요?

2022-03-22 09:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    }
추가적으로 getter와 같은 메서드 보다는 비즈니스 로직을 담당하는 메서드를 위에 배치하면 좋을 것 같네요.

2022-03-22 09:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
>          return getReviewContent().getTitle();
reviewContent같은 경우는 Review의 필드인데 바로 접근하지 않고 getter를 사용하신 이유가 있나요?
```suggestion
    public String getTitle() {
        return reviewContent.getTitle();
```

2022-03-22 09:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
>      public String getAuthorName() {
이런 부분들도 값을 보내주기 위해서면 필요하긴 하겠지만 바로 get.get.get 보다는 객체에 물어보는게 좀 더 나을 것 같네요.
member.getName(); -> member 내부에서 profile.getNickname() 리턴 하는 느낌?

2022-03-22 09:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/ReviewDtoAssembler.java
> +public class ReviewDtoAssembler {
오 Assembler를 사용하셨네요!
Assembler를 사용하신 이유가 궁금하네요! 어떤 면 때문에 Assembler를 사용하셨나요??

2022-03-22 09:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @PostMapping("/shops/{shopId}/reviews")
자원을 저장하는 주체가 review 이므로 `POST /reviews`는 어떻게 생각하시나요? 개인적으로 shopId는 @RequestBody로 받아와도 될 것 같다는 생각이 드네요.

/shops로 시작하게 되면 shop 패키지 내부에 review가 포함되는 것 처럼 느껴지는데, shop마다 review를 달긴 하지만 별개로 관리할 수 있다고 생각이 들기도하네요. 

이 부분은 같이 얘기해보면 좋을 것 같네요.

2022-03-22 09:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/dto/response/ReviewResponse.java
> +    private List<MultipartFile> images;
보통 백엔드에서 프론트로 이미지가 저장된 url이 아닌 이미지 자체를 보내주는가요? 이미지 처리를 안해봐서 잘 모르겠네요

2022-03-22 09:57 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/review/application/ReviewServiceTest.java
>  class ReviewServiceTest {
클래스 내부를 보니 통합테스트를 진행하는 것 같아요. 
ServiceTest라고 클래스명을 두면 서비스단 단위테스트를 진행한다는 느낌이 들어서 IntegrationTest라고 네이밍하는게 더 좋아 보여요

2022-03-22 09:57 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/review/application/ReviewServiceTest.java
> +
띄어쓰기가 2줄이네요 ㅎㅎ

2022-03-22 10:30 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    public ReviewResponseDto create(ReviewCreateRequestDto reviewCreateRequestDto) {
아 그 부분을 모르고 있었습니다!! 하나 배워갑니다!!

2022-03-22 10:33 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
>      public String getAuthorName() {
그 방법이 더 낫겠네요!!

2022-03-22 11:00 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/dto/ReviewDtoAssembler.java
> +public class ReviewDtoAssembler {
Dto 내부에는 getter와 setter를 제외한 method를 사용하는 것을 권장하지 않는다라고 알고 있습니다. 그래서, dto를 entity로 변환하는 로직을 다른 객체에서 하기 위해서, Assembler를 사용했습니다!!

2022-03-22 11:03 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    @PostMapping("/shops/{shopId}/reviews")
댓글을 작성하려면, 원하는 shop으로 들어가고, 그 안에서 댓글을 작성하는 것이기 때문에, POST /shops/{shopId}/reviews로 들어가는게 좀 더 자연스러울 거 같다고 생각해 작성했습니다.
마이페이지에서 발자국으로 자신이 작성한 모든 리뷰를 볼 때도 같이 얘기해보면 좋을 거 같습니다!

2022-03-22 11:07 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/presentation/dto/response/ReviewResponse.java
> +    private List<MultipartFile> images;
s3를 프론트엔드에서 직접 접근하는 것 보다, 백엔드에서 s3에 접근해서 저장하고, 그것에 해당하는 url를 보내주는 게 좀 더 자연스럽지 않을까? 라는 생각이 듭니다!!

이전 프로젝트에서도 그렇게 진행은 했습니다!! 이 부분은 프론트 엔드 개발자들과 함께 얘기해보면 좋을 거 같습니다:)

2022-03-22 11:07 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/review/application/ReviewServiceTest.java
> +
넵ㅎㅎ

2022-03-22 11:13 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/review/application/ReviewServiceTest.java
>  class ReviewServiceTest {
넵!!ㅎㅎ

2022-03-23 03:59 UTC, KJunseo requested changes
마지막으로 몇가지만 얘기해보고 approve하면 될 것 같네요! 고생하셨습니다. 한 번만 더 확인부탁드립니다!
++ 현재 사용하지 않는 import들이 있어서 마지막에 전체적으로 한 번 체크해보면 좋을것 같아요

2022-03-23 03:59 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewImages.java
> +    public void addReviewImages(Review review) {
메서드명이 조금 어색한 것 같습니다! reviewImage들에 review와의 연관관계 매핑을 해주는 메서드인데 `addReviewImages`는 조금 어색한 것 같아요!

2022-03-23 03:59 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    }
보통 클래스 내부에 배치되는 요소들의 순서는
```
    상수
    클래스 변수
    인스턴스 변수
    생성자
    팩토리메서드
    메서드
    기본 메서드(equals, hashCode, toString...)
```
입니다. getter의 경우 기본 메서드에 가깝다고 볼 수 있기 때문에 `addReviewImages()`를 위에 배치하는게 좋을 것 같습니다.

2022-03-23 03:59 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/dto/ReviewAssembler.java
> +public class ReviewAssembler {
assembler 사용시 private 기본 생성자를 만들어서 인스턴스화를 막아주는 게 좋을 것 같네요. 추가적으로 두 개의 assembler 클래스 내부에 사용하지 않는 메서드가 있는 것 같습니다!

2022-03-23 03:59 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/dto/response/ReviewResponse.java
> +    private List<MultipartFile> images;
url을 보내준다면 MultipartFile 대신 String이 들어가야 할 것 같네요

2022-03-23 03:59 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewServiceTest.java
> +class ReviewIntegrationTest {
클래스 이름을 변경할 때는 패키지 구조를 보고 거기서 변경해줘야할 것 같아요!
현재는 이런식으로 되어있습니다!
<img width="312" alt="스크린샷 2022-03-23 오후 12 56 25" src="https://user-images.githubusercontent.com/45876793/159621140-a250bce0-3c61-447e-99a8-b31ab053ff88.png">

2022-03-23 03:59 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewServiceTest.java
> +import org.springframework.test.annotation.Rollback;
사용하지 않는 import

2022-03-23 03:59 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewServiceTest.java
> +import com.handong.rebon.review.presentation.dto.response.ReviewResponse;
사용하지 않는 import

2022-03-23 04:45 UTC, gomster96 approved these changes
수고 많이하셨습니다. 몇가지 궁금증이 있어서 코멘트에 답 해주시면 감사하겠습니다!

2022-03-23 04:45 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
궁금해서 여쭤봅니다! AllArgsConstructor는 외부에서는 쓰지 않기 때문에 private로 막아주신건가요?

2022-03-23 04:45 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +        this(title, content, "");
혹시 Builder 패턴을 사용하시지 않고 이렇게 하신이유는 null 값이 들어가지 않도록 하기 위해서 이렇게 하신건가요?

2022-03-23 04:45 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/presentation/dto/response/ReviewResponse.java
> +    private List<MultipartFile> images;
저도 평강킴님의 말씀에 동의합니다.

2022-03-23 05:43 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    }
감사합니다!

2022-03-23 05:43 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/presentation/dto/response/ReviewResponse.java
> +    private List<MultipartFile> images;
그렇겠네요!!

2022-03-23 05:46 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewContent.java
> +        this(title, content, "");
네 맞습니다:)

2022-03-23 07:57 UTC, KJunseo approved these changes
리뷰를 많이 드린 것 같은데 고생하셨습니다!
conflict 부분만 해결하시면 될 거 같네요

2022-03-23 11:42 UTC, merged