[#5] 관리자 단일 가게 생성 기능 구현
RE-BON/ReBoN pull request #59
Opened 2022-03-17 15:44 UTC by KJunseo

### Description
- 새로운 Shop 등록 로직 개발(단일 Shop)
- 어댑터 패턴을 사용하여 카테고리에 맞는 구현체 생성 
- 레스토랑과 카페의 경우 메뉴추가 로직도 수행
- 관리자 페이지와, 이미지 저장 기능은 추후에 개발할 예정

### Trouble Shooting

### ETC
- cascade 옵션은 완전히 소유하는 엔티티의 경우만 사용하는 것이 좋다.(https://www.inflearn.com/questions/31969)
- 패키지 구조 수정이 필요해보임(메뉴, 카테고리, 태그 등)

2022-03-18 05:30 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/exception/shop/ShopNameException.java
> +}
Shop을 추가하는데에 아래에서 보니 잘못된 이름은 빈 문자열이나 그냥 띄어쓰기를 나타내는것 같은데, Exception을 "빈 문자열이 입력되었습니다." 뭐 이런느낌으로 하는게 더 낫지 않나요?

2022-03-18 05:30 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
여기를 따로 AcessLevel을 PROTECTED 로 해주신 이유가 궁금합니다.

2022-03-18 05:30 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +        this.shopTags.addAll(shopTags);
이렇게 스트림을 사용해서 생성하는 부분 많이 흥미롭네요. 잘 배우고 갑니다! 👍

2022-03-18 05:30 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/domain/shop/ShopTest.java
> +    }
이렇게 extracting을 통해 더 가독성 좋게 확인할 수가 있군요..!

2022-03-18 05:30 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +    private final List<Like> likes = new ArrayList<>();
여기서 final을 추가하면 어떤 역할을 하나요??

2022-03-18 05:43 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
엔티티 같은 경우는 파리미터가 없는 생성자(public or protected)가 필요합니다.
JPA는 DB 데이터를 객체로 주입할 때 기본 생성자로 객체를 생성하고 reflection을 통해 값을 매핑해주는 식으로 동작하기 때문입니다.
따라서 기본 생성자는 만들어줘야하는데 public보다는 protected가 좀 더 무분별한 객체 생성을 막을 수 있기 때문에 protected로 두었습니다!

2022-03-18 05:44 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +        this.shopTags.addAll(shopTags);
스트림이 가독성도 좋은 것 같아요!! 저도 flatMap은 아직 잘 못써서..

2022-03-18 05:51 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +    private final List<Like> likes = new ArrayList<>();
아 entity의 경우 필드에 final을 쓰면 안된다고 알고 있는데 습관적으로 붙인 것 같네요. 수정하겠습니다!

2022-03-18 06:00 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/Shop.java
> +    private final List<Like> likes = new ArrayList<>();
[참고]
엔티티 필드에 final이 올 수 없는 이유
-> 엔티티 클래스는 JPA에 의해 프록시 객체로 확장되는데 이때 reflection을 사용. reflection은 기본 생성자를 통해 프록시 객체를 만들고 setter를 사용해 초기화 함. final 필드는 setter를 사용할 수 없어서 엔티티 필드를 final로 가지면 안된다.

2022-03-18 08:07 UTC, PyeongGangKim requested changes

2022-03-18 08:07 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/presentation/dto/request/ShopRequest.java
> +public class ShopRequest {
setter annotation을 추가해줘야지 ModelAttribute로 받을 수 있을 거 같아요!!

2022-03-21 08:56 UTC, PyeongGangKim approved these changes
확인했습니다! 고생하셨습니다~!

2022-03-21 13:54 UTC, gomster96 approved these changes
제 리뷰가 전부 반영되어서 기쁩니다. 수고하셨습니다 👍

2022-03-21 14:30 UTC, merged