[#3]: 태그 생성 기능
RE-BON/ReBoN pull request #60
Opened 2022-03-19 14:15 UTC by leehyelim0691

### Description
태그 생성 기능

### Trouble Shooting

### ETC

2022-03-20 06:39 UTC, KJunseo requested changes
의견 남겨봤습니다! 모두 반영하실 필요는 없고 코멘트 달아주시면 좋을 것 같네요! 다시 리뷰 요청 주세요

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +    TagRepository tagRepository;
@Autowired를 사용하신 이유가 있을까요?
필드인젝션을 사용하면 외부에서 변경이 불가능하다는 단점이 있어 테스트를 작성하기에 쉽지 않을 것 같아요.

저는 생성자 주입을 사용하는게 좋아보여요! 스프링 의존성 주입 방법에 대해 알아보시면 좋을 것 같네요!

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +    }
public Long createTag(String name), public Long createTag(TagRequestDto tagRequestDto)

두 방법의 로직이 동일해보여요. 둘 중 하나만 사용해도 되지 않을까요??

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +            throw new TagExistException();
`if (tagRepository.existsByName(name))` 이런식으로 처리해도 될 것 같습니다.
추가적으로 if문 내부 로직이 한 줄이어도 가독성을 위해 { }를 붙여주는 것이 좋을 것 같아요!

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +                .build();
태그 같은 경우는 필드가 하나뿐이어서 빌더 패턴말고 일반 생성자를 사용하는것도 괜찮아 보이긴 하네요

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +        return newTag.getId();
이렇게 해줘도 JPA에 의해 id값이 들어갈 것 같긴하지만 가독성을 위해 새로 반환되는 값을 사용하는 건 어떨까요??
```suggestion
        Tag savedTag = tagRepository.save(newTag);
        return savedTag.getId();
```

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +    }
엔티티 자체를 presentation단으로 넘기는 건 좋지 않아보여요!

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/dto/TagRequestDto.java
> +    private Long id;
처음 태그를 생성할 때 id값은 존재하지 않을 것 같아요!

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +@NoArgsConstructor
access 레벨을 Protected로 줘도 좋을 것 같네요!

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    private List<ShopTag> shopTags = new ArrayList<ShopTag>();
```suggestion
    private List<ShopTag> shopTags = new ArrayList<>();
```

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    }
롬복 @Getter나 이 메서드들 둘 중 하나만 사용해도 될 것 같아요

2022-03-20 06:39 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +    }
현재 실제 repository를 사용해서 값을 저장하고 있는데요. 이 경우는 JPA가 제대로 동작하는가를 테스트하는 것 같아요. TagService를 주입받아서 service의 createTag()를 호출해보는 식으로 테스트를 진행해야 될 것 같아요!

2022-03-20 06:39 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +        }
이 부분에 대한 단위 테스트도 진행하면 좋을 것 같아요!

2022-03-21 03:21 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +    TagRepository tagRepository;
네! 감사합니다 :)

2022-03-21 03:29 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +    }
그렇네요! 둘 중 하나로 수정하겠습니다

2022-03-21 03:30 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +            throw new TagExistException();
오 좀 더 간결하게 쓸 수 있는 방법이 있었네요! 감사합니다 :)

2022-03-21 03:32 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +                .build();
좋은 의견 감사합니다!

2022-03-21 03:36 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +        return newTag.getId();
이렇게 보니, 반환 값을 받는게 훨씬 좋아보이네요! 감사합니다!

2022-03-21 05:27 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +@NoArgsConstructor
아 그렇게 하면 되겠네요! 감사합니다

2022-03-21 05:32 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +    }
앗 네 그렇군요!! 수정하도록 하겠습니다 감사합니다!

2022-03-21 05:32 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +        }
좋은 의견 감사합니다!! :)

2022-03-21 05:47 UTC, PyeongGangKim requested changes
고생하셨습니다!!

2022-03-21 05:47 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/exception/tag/TagExistException.java
> +    }
"이미 존재하는 태그입니다"라고 표현하는 것이 좀 더 명확한 메세지가 되지 않을까 싶어요!!

2022-03-21 05:47 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    @OneToMany(mappedBy = "tag", fetch = FetchType.LAZY)
OneToMany일때는 default FetchType이 Lazy여서 명시를 안해줘도 될 거 같아요!!

2022-03-21 06:24 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/exception/tag/TagExistException.java
> +    }
네!! 좋은 의견 감사합니다 :)

2022-03-21 06:25 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    @OneToMany(mappedBy = "tag", fetch = FetchType.LAZY)
아 그렇군요!  수정하도록 하겠습니다. 감사합니다!!

2022-03-21 13:24 UTC, gomster96 reviewed
관리자 페이지를 구현 하시는데 React를 사용하셨네요. 프론트엔드 코드가 좀 들어가있는거 같은데 의도하신건가요?

2022-03-21 13:24 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    }
@getter 쓰면 편해요 ㅋㅋ

2022-03-21 13:24 UTC, gomster96 commented on FrontEnd/.vscode/settings.json
> +    "files.exclude": {
혹시 dev를 갑자기 merge하신 이유가 있을까요?? 갑자기 frontcode가 들어와서 궁금해서 여쭤봅니다!

2022-03-21 14:29 UTC, gomster96 requested changes
관리자 페이지를 구현 하시는데 React를 사용하셨네요. 프론트엔드 코드가 좀 들어가있는거 같은데 의도하신건가요?

2022-03-22 11:43 UTC, leehyelim0691 commented on FrontEnd/.vscode/settings.json
> +    "files.exclude": {
아니요ㅠ 실수로 들어와 진 것 같습니다ㅠ!

2022-03-23 03:26 UTC, PyeongGangKim requested changes
고생하셨습니다!! 몇 개 리뷰 남겼으니, 확인부탁드려요~!!

2022-03-23 03:26 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +    void createTag() {
Rollback을 false로 하신 이유가 있으신가요?
false로 두면, 테스트를 여러번 했을 때, 이미 존재하는 태그라고 나옵니다!!

테스트 데이터가 실제 서비스하는 DB에도 들어갈 가능성이 있기 때문에, Rollback을 true로 두는 것이 좋을 거 같아요:)

2022-03-23 03:26 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +    }
이 test는 assertThatThrownBy를 사용해서 TagNameException을 잡아주는 게 더 좋아보여요!!

현재 상태로 돌리니 TagNameException이 나와서, test에 통과하지 못합니다:)

2022-03-23 03:26 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/dto/TagRequestDto.java
> +}
필드가 하나 뿐이여서, Builder가 아닌, 일반 생성자만 사용해도 될 거 같아요:)

2022-03-23 03:37 UTC, KJunseo requested changes
좀 더 얘기해보면 좋을 것 같은 부분이 있어 리뷰 남겼습니다! 확인 후 다시 요청해주세요

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +@Transactional
이렇게 서비스 클래스 전체에 `@Transactional`을 붙여줄 경우 `@Transactional(readOnly = true)`옵션을 주고, 읽기작업이 아닌 메서드 위에 `@Transactional`을 붙여주는 게 좋아보여요. 클래스단에 그냥 `@Transactional`을 붙이는 경우 하위에 읽기 작업만 있어도 readOnly 옵션을 빼먹을 가능성이 있을 것 같아요!

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +    }
findByName을 통해 검증을 하고 싶다면 이렇게 줄일 수 있겠네요
```suggestion
    private void validateDuplicateTag(String name) {
        tagRepository.findByName(name)
                                .orElseThrow(TagExistException::new);
    }
```
```suggestion
    private void validateDuplicateTag(String name) {
        if (tagRepository.existsByName(name)) {
            throw new TagExistException();
        }
    }
```

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +//    }
사용하지 않는 메서드는 지우는게 좋을 것 같아요!!

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/dto/TagRequestDto.java
> +@Builder
필드가 단 한개여서 굳이 빌더를 쓰지 않아도 될 것 같은데 어떻게 생각하시나요?

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/dto/TagRequestDto.java
> +//    private Long id;
사용하지 않는 코드는 주석처리가 아니고 지우는게 좋을 것 같아요!

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
>  public class Tag {
```suggestion
@AllArgsConstructor
public class Tag {
```

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    private List<ShopTag> shopTags = new ArrayList<>();
지금 당장 사용하진 않지만 fetchType을 Lazy로 줘도 좋을 것 같네요

2022-03-23 03:37 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +class TagIntegrationTest {
현재 저장되어 있는 태그와 같은 이름으로 태그 등록을 하려고 할 때 예외처리가 일어나고 있는데, 이 부분에 대한 테스트가 없는 것 같습니다!

추가적으로 궁금한 것이 `@Rollback` 어노테이션을 붙여주신 이유가 있을까요??

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    }
평강이 pr 중에 `backend/src/test/java/com/handong/rebon/unit/review/domain/content/ReviewContentTest.java` 이 부분을 참고해서 도메인 단 단위 테스트도 진행하면 좋을 것 같아요! 

현재는 통합테스트만 있는 것 같은데, 도메인 단위테스트가 통합테스트 보다 먼저 진행되어야 한다고 생각해요!

2022-03-23 03:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +                .build();
혹시 빌더의 어떤 부분 때문에 빌더를 사용하셨을까요??

2022-03-23 07:39 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +    void createTag() {
앗 네! 제가 테스트를 해보다가 깜빡하고 수정을 안해둔 것 같네요. 감사합니다! :)

2022-03-23 07:48 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/dto/TagRequestDto.java
> +}
그렇군요! 감사합니다!!

2022-03-23 08:07 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +@Transactional
아 그렇군요,,! 처음 알게 된 사실이네요!! 자세히 설명해주셔서 감사합니다 :)

2022-03-23 08:10 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +    }
아 이렇게 더 코드가 간결해질 수 있겠군요!! 감사합니다 :)

2022-03-23 08:18 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +//    }
앗 이부분을 실수로 안지웠네요ㅠ 감사합니다!

2022-03-23 08:18 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/dto/TagRequestDto.java
> +@Builder
네!! 빌더를 쓰지 않아두 될 것 같아요 감사합니다!

2022-03-23 08:19 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/dto/TagRequestDto.java
> +//    private Long id;
넵 깜빡했네요ㅠ 감사합니다!!

2022-03-23 08:21 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
>  public class Tag {
감사합니다ㅏ!!

2022-03-24 09:52 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    private List<ShopTag> shopTags = new ArrayList<>();
그 OneToMany일때는 default FetchType이 Lazy여서 명시를 따로 안해주었는데, 혹시 지금 반드시 해야할 이유가 있을까요!! :) ?

2022-03-25 13:57 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    }
네! 제가 단위 테스트를 안했었군요 감사합니다!

2022-03-25 13:57 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +                .build();
제가 생성자로 다시 바꾸었는데 변경이 안된 것 같아요! 감사합니다!

2022-03-25 13:58 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +class TagIntegrationTest {
네! 테스트 처리 하였습니다. Rollback은 실제로 데이터에 들어오는지 확인할려고 하였고, 다시 수정하였습니다!

2022-03-26 14:57 UTC, PyeongGangKim requested changes
고생하셨습니다!
리뷰 남긴거 확인부탁드려요:)

2022-03-26 14:57 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/application/dto/TagRequestDto.java
> +}
현재 사용하고 있지 않는 class인거 같아요

2022-03-26 14:57 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/unit/tag/domain/content/TagContentTest.java
> +    @DisplayName("태그 이름이 null이거나 빈 문자열이면 생성할 수 없다.")
null일 경우는 test를 하지 않는 거 같아요!

2022-03-27 03:32 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/dto/TagRequestDto.java
> +}
앗 네 제가 실수로 안지웠네요 감사합니다!!

2022-03-27 03:32 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/unit/tag/domain/content/TagContentTest.java
> +    @DisplayName("태그 이름이 null이거나 빈 문자열이면 생성할 수 없다.")
그 문자열이 비어있을 때, 태그를 생성할 수 없다는 exception을 보내려면 이 테스트도 필요하지 않나요?!

2022-03-27 03:46 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +        }
컨벤션에 맞게 띄어쓰기를 추가하면 좋겠네요!
(맥 기준 단축키 opt + cmd + l)
```suggestion
        if (tagRepository.existsByName(name)) {
            throw new TagExistException();
        }
```

2022-03-27 03:46 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/domain/Tag.java
> +    private List<ShopTag> shopTags = new ArrayList<>();
아 굳이 안해줘도 될 것 같네요!

2022-03-27 03:56 UTC, KJunseo requested changes
마지막 리뷰가 될 것 같네요! 고생하셨습니다! 한 번 확인해보시고 요청주세요!

2022-03-27 03:56 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/presentation/AdminShopTagController.java
>  public class AdminShopTagController {
이 컨트롤러가 필요한가요?

2022-03-27 03:56 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/unit/tag/domain/content/TagContentTest.java
> +public class TagContentTest {
Tag같은 경우 TagContent라는 클래스가 없는데 이름을 이렇게 해두신 이유가 있으신가요??

2022-03-27 03:56 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/application/dto/TagRequestDto.java
> +public class TagRequestDto {
서비스 코드로 Dto를 넘기지 않을 거라면 필요없어 보이네요! 사용할 것이라면 서비스 코드 수정이 필요해보입니다

2022-03-27 04:50 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/unit/tag/domain/content/TagContentTest.java
> +    @DisplayName("태그 이름이 null이거나 빈 문자열이면 생성할 수 없다.")
넵 필요할 거 같은데, 파라미터로 주어지는 것에 null이 없는데, display에는 null일 경우를 체크한다고 써있어서요!!

2022-03-27 08:13 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/unit/tag/domain/content/TagContentTest.java
> +    @DisplayName("태그 이름이 null이거나 빈 문자열이면 생성할 수 없다.")
아 제가 잘못 이해했었네요!! 네 감사합니다!!

2022-03-27 13:33 UTC, gomster96 approved these changes
수고하셨습니다! 다른분들이 고치라고 한것만 고치시면 될거같네요! ㅎㅎ 파이팅입니다.

2022-03-27 13:33 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +                .orElseThrow(TagExistException::new);
여기부분 별건아니지만, cmd + option + L 로 정렬해주면 좋을거같아요!

2022-03-27 13:33 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +        assertThat(newTag.getName()).isEqualTo(tagName);
참고로! 당연히 getName() 테스트할땐 쓰셔도 되지만, 저도 최근에 알았는데 이게 가독성이 좋은거 같더라구요. 물론 취향차이일거같습니다. assertThat(newTag).extracting("name").isEqqualTo(tagName)
이렇게 쓰실수도 있습니다!

2022-03-28 03:35 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +        }
앗 네 수정하도록 하겠습니다!!

2022-03-28 03:36 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/presentation/AdminShopTagController.java
>  public class AdminShopTagController {
혹시 몰라서 만들어두었는데 필요가 없었던 것 같아요 삭제하도록 하겠습니다!

2022-03-28 03:37 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/unit/tag/domain/content/TagContentTest.java
> +public class TagContentTest {
테스트 이름을 다른 것들을 보고 참고하다 만들어두었던 것 같아요 수정하도록 하겠습니다!! :)

2022-03-28 03:38 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/dto/TagRequestDto.java
> +public class TagRequestDto {
네 감사합니다!!

2022-03-28 03:38 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/shop/domain/tag/application/TagService.java
> +                .orElseThrow(TagExistException::new);
네!! 감사합니다 !!

2022-03-28 03:43 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
> +        assertThat(newTag.getName()).isEqualTo(tagName);
앗 그렇군요!! 감사합니다 !

2022-03-28 05:43 UTC, PyeongGangKim approved these changes
리뷰가 잘 반영되어 있네요!!
고생많으셨습니다:)

2022-03-28 07:27 UTC, KJunseo approved these changes
이만 어푸르브 하겠습니다!! 고생많으셨어요!
패키지 구조 신경쓰면서 conflict 난 부분들만 잘 처리하고 머지하면 될 것 같네요!

2022-03-28 13:55 UTC, leehyelim0691 commented
[#3] 태그 생성 기능

2022-03-29 00:21 UTC, merged