[#56] 리뷰 목록 조회
RE-BON/ReBoN pull request #84
Opened 2022-03-29 11:23 UTC by PyeongGangKim

### Description
- admin에서 title과 tip으로 리뷰를 검색할 수 있는 기능 구현
- admin에서 모든 리뷰를 가져올 수 있는 기능 구현
- admin에서 단일 리뷰를 가져올 수 있는 기능 구현
- api에서 가게가 가지고 있는 리뷰를 가져올 수 있는 기능 구현
- api에서 유저가 자신이 쓴 리뷰를 가져올 수 있는 기능 구현

### Trouble Shooting
- Review에서 member와 shop을 가져올 때, 생길 수 있는 N+1 문제를 fetch join으로 해결.
- Review에서 reviewImages를 가져올 때, 생길 수 있는 N+1 문제를 default_batch_size 설정으로 문제 해결.
- builder 어노테이션 사용시 List필드를 초기화를 해도, builder로 만든 객체를 사용할 때, 해당 필드가 null 문제가 발생함. @Builder.default를 해당 필드에 사용하여 문제 해결.

### ETC

2022-03-30 04:58 UTC, gomster96 requested changes
몇가지 질문을 올렸습니다! 관련해서 커멘트 부탁드립니다! 
review부분이 많이 복잡한데 너무 멋지게 구현하셨네요. 얼마나 고민하셨는지가 잘 보입니다. 그리고 어셈블러 사용하는 부분 잘 배웠습니다~ 
그리고 특별히 이번에만 Assigner 를 추가해드릴게요. Assigner 추가하는거 깜빡하신거같아서 ㅎ

2022-03-30 04:58 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +
보면서 궁금해서 찾아봤는데 이렇게 Like문을 처리해주면 되네요. findAllByContains, findAllByContaining, findAllByIsContaining 이렇게 3개가 있는데 다 똑같은 기능이라고 합니다 ㅎㅎ 어떤 블로그에 아저씨는 그래서 제일 짧은 Contains 를 쓴답니다.  아무튼 또 배우고갑니다

https://www.memoengine.com/blog/spring-data-jpa-contains-containing-iscontaining/

2022-03-30 04:58 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = reviewRepository.findAllByMemberId(memberId);
개인적으로 뭔가 네이밍이 findByMemberId 라고 하면 단건의 Member를 찾아오는거 같아서 다른 메소드명으로 하면 좋을거같아요. JPA에서 이미 제공하는  findByMemberId 하면 단건을 가져오는데, 메소드명은 findByMember고 실제 그 안에서 사용하는 기능은 findAllByMember니까 약간 메소드명이 헷갈려요. 제가 맞는지는 모르겠지만 저는 findMembersById  뭐 이렇게 바꿀수도 있을거같은데, 이건 어떻게 할지 의견을 들어보고 싶군요!

2022-03-30 04:58 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
😛

2022-03-30 04:58 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    @Builder.Default
이 Builder.Default 를 찾아보니 인스턴스 생성시 default value를 넣어주고 싶을 때 사용하는것 같더라구요.  사용해서 저번에 말씀하셨던, Builder를 사용했을 때 ArrayList()에 null이 발생하던 문제를 이렇게 해결하신 걸까요?

2022-03-30 04:58 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = reviewRepository.findAllByMemberId(memberId, pageable);
pageable 을 사용하셨는데,  제가 찾아본 곳에서는 페이징을 하려면 타입을 Page<Review> 이런식으로 해야하는 것 같았는데, 이렇게 그냥 List 를 반환해주어도 똑같이 작동하나요?

2022-03-30 06:57 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +
감사합니다!! title을 빼면 저렇게 사용할 수 있겠네요!! 근데 저렇게 사용하면 fetch join도 사용할 수 있나요??

2022-03-30 07:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    @Builder.Default
네네 builder를 사용하면 각 필드와 생성자 그리고 setter를 가지는 inner class가 만들어져서, 필드에서 초기화한 내용은 적용되지 않는다고 합니다! 그래서 해당 문제를 해결하기 위해 @Builder.Default 어노테이션을 사용했습니다.

밑에 블로그를 보시면 더 자세히 이해하실 수 있으실 거에요!
https://velog.io/@hsbang_thom/Lombok-Builder.Default

2022-03-30 07:02 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = reviewRepository.findAllByMemberId(memberId, pageable);
그 부분은 좀 더 찾아보고 다시 고쳐봐야 될 거 같습니다,,!!

2022-03-30 07:10 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = reviewRepository.findAllByMemberId(memberId);
말씀 들으니까 그게 맞을 거 같네요!! 그럼 findReviewsByMemberId는 어떨까요??

2022-03-30 07:16 UTC, KJunseo requested changes
고생하셨습니다! 리뷰 늦게 드려서 죄송합니다.
몇 가지 리뷰 남겼는데 확인해보시고 다시 요청주세요!

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = new ArrayList<>();
새로 할당해주신 이유가 있으신가요? 로직을 보니 keyword가 없을 때와 keyword가 있을 때 List<Review>를 반환받아 각각 처리하는 것으로 보이는데 따로 변수를 둔 이유가 궁금합니다

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        if (keyword == null) {
직접 null 체크를 해주고 계신데 `StringUtils.hasText(keyword)` 같은 메서드를 사용하시는 건 어떠신가요?

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +            reviews = reviewRepository.findAll(pageable).toList();
오 Page에서 데이터를 꺼낼 때 `getContent()`를 통해 꺼내는 예시를 많이 접했는데 `toList()`도 동일한 역할을 하는건가요?

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
문자열 연산을 할 때 `+`연산은 매번 새로운 인스턴스를 생성하는 비용이들어서  비효율적이라고 알고 있어요.  StringBuilder같은 append() 메소드를 이용한 연산 비용이 더 싸다고 알고 있습니다!

추가적으로 이 메서드는 ReviewService보다는 util이라는 패키지를 만들어서 static 메서드로 관리해도 괜찮을 것 같다는 생각이 드네요

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    @Transactional
읽기 작업만 일어나는 곳은 readOnly 옵션을 주는 건 어떤가요?

readOnly 옵션을 주게되면 영속성 컨텍스트에서 더티체킹을 하지 않게됩니다. 데이터를 읽어올 것이 많은 경우, 더티 체킹을 꺼놓으면 성능상 이점이 있습니다.

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/repository/ReviewRepository.java
> +    @Query("select r from Review r join fetch r.member join fetch r.shop where r.reviewContent.content like :keyword or r.reviewContent.tip like :keyword")
이 쿼리는 줄을 나눠서 적어주는게 좀 더 가독성 있을 것 같아요. 추가적으로 인텔리제이는 아래 그림과 같이 기준선을 보여주는데 이 선을 넘어가지 않는 것이 가독성이 좋을 것 같네요

<img width="992" alt="스크린샷 2022-03-30 오후 3 31 17" src="https://user-images.githubusercontent.com/45876793/160766204-4ca2968c-cb9b-4aa7-bb71-8b31ae028889.png">

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/ReviewDtoAssembler.java
> +                      .map(review -> adminReviewResponseDto(review))
람다 메서드참조로 바꿀 수 있을 것 같아요!
```suggestion
                      .map(ReviewDtoAssembler::adminReviewResponseDto)
```

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/response/AdminReviewResponseDto.java
> +    private double star;
int로 바꿔야할 것 같네요

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    public List<ReviewResponseDto> findByMemberId(ReviewRequestDto reviewRequestDto) {
이 메서드가 발자국 기능에 쓰이는 메서드인가요??

현재 `ReviewResponseDto`와 `ReviewRequestDto`가 여러 메서드에서 쓰이고 있는 것 같아요.
제가 예전에 받은 리뷰를 공유해드리면 요청별로 dto를 다르게 두는 것이 좋다고 하더라고요. dto같은 경우는 변경이 자주 일어나기 때문에 공통적으로 사용하다보면 여러 메서드에 영향을 끼칠 수 있을 것 같아요.

`ReviewResponseDto` 같은 경우 발자국이랑, 가게 별 리뷰 목록을 반환할 때 사용되는 타입인 것 같은데, 피그마를 보면 발자국 기능에서는 작성자 정보는 따로 필요하지 않은데도 값을 넣어주는 것을 볼 수 있어요

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        Member member = memberRepository.findById(memberId).orElseThrow(MemberNotFoundException::new);
순서상 member를 먼저 검증하고 -> 찾은 member를 통해 리뷰를 찾는 식이 좀 더 자연스러울 것 같아요!

추가적으로 지금은 member 기능이 구현되지 않아서 어쩔 수 없지만 후에 인터셉터를 이용해서 member 검증이 이루어져서 이 메서드가 조금 변형이 있을 것 같네요

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
이 메서드가 가게별 리뷰 목록을 반환하는 메서드일까요??

request로 넘어오는 memberId가 어떻게 사용되고 있나요? 가게별 리뷰 목록을 가져오려면 review의 shop을 통해 가져오면 된다고 생각하는데, memberId가 어떤값인지를 모르겠어요

가게 별 리뷰 목록 같은 경우는 작성자가 모두 다를텐데 어떤 member가 입력으로 들어오는 건지 잘 모르겠어요!

추가적으로 shopId를 통해 shop을 가져오고 shop이 유효하다면 shop을 통해 review를 가져오는 식은 어떤가요?

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/dto/response/AdminReviewResponse.java
> +public class AdminReviewResponse {
사용하지 않는 클래스인 것 같아요!

2022-03-30 07:16 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    ) {
블러처리는 프론트에서 처리할 것 같아서 이 요청은 유저가 없어도 되지 않나요??

2022-03-30 07:34 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
memberId는 현재 shop에 대한 review를 요청한 member를 찾을 때 사용됩니다. member를 찾아오는 이유는 각 리뷰들에 대해 공감여부를 표시해줘야 되기 때문에 입니다!

shop을 가져오고, 검증하고, review를 한번 더 가져오는 게 좀 더 안전한 코드가 될 거 같네요! 감사합니다!

2022-03-30 07:35 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/presentation/ApiReviewController.java
> +    ) {
리뷰에 대해 공감처리를 해줘야 할 때, 리뷰를 받아오는 것이 필요할 거 같습니다!

2022-03-30 07:35 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        Member member = memberRepository.findById(memberId).orElseThrow(MemberNotFoundException::new);
그게 자연스러울 거 같네요!! 감사합니다!

2022-03-30 07:38 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    public List<ReviewResponseDto> findByMemberId(ReviewRequestDto reviewRequestDto) {
각각을 분리하는 게 나중에, 변경이 일어났을 때 더 좋을 거 같네요
감사합니다:)

2022-03-30 08:59 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = reviewRepository.findAllByMemberId(memberId);
아 ㅋㅋ findMembersById 라니 잘못된 이름을 말했네요 ㅋㅋㅋㅋㅋ

2022-03-30 20:35 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +            reviews = reviewRepository.findAll(pageable).toList();
제가 잘못쓴거 같네요,,,,

2022-03-30 20:42 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    @Transactional
그렇군요!! 또 하나 배워갑니다!

2022-03-30 20:46 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +        List<Review> reviews = new ArrayList<>();
반환을 받는데, 굳이 list를 할당할 필요가 없을 거 같네요!! 착각을 하고 만들었던 거 같습니다!

2022-03-30 20:48 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/repository/ReviewRepository.java
> +    @Query("select r from Review r join fetch r.member join fetch r.shop where r.reviewContent.content like :keyword or r.reviewContent.tip like :keyword")
기준선이 존재하는 지는 몰랐네요!! 감사합니다

2022-03-31 07:57 UTC, KJunseo requested changes
고생하셨습니다! 한 번만 더 얘기해보고 싶은 부분있어서 리뷰 남겼습니다! 다시 요청 주세요!

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +            List<Review> reviews = reviewRepository.findAllByReviewContentAndTipContaining(StringUtil.makeContainingKeyword(keyword), pageable)
이 부분도 가로로 너무 길어 `StringUtil.makeContainingKeyword(keyword)`을 변수로 둔다던지 해서 줄을 나누면 좋을 것 같아요!

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +
공백 2줄!

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/util/StringUtil.java
> +public class StringUtil {
이런 클래스는 private 생성자를 둬서 인스턴스화를 막아도 좋을 것 같네요!

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/dto/response/ReviewGetByShopResponseDto.java
> +import java.time.LocalDate;
사용되지 않는 import!

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    public List<ReviewGetByMemberResponseDto> findReviewsByMember(ReviewGetByMemberRequestDto reviewGetByMemberRequestDto) {
이 부분은 그냥 제 의견을 말씀드리자면, review 패키지안의 review 서비스라서 뭔가 당연히 review를 반환해줄 것 같은 느낌이어서 굳이 reviews를 추가해야하나 싶은 생각이 들어요. 중복이라는 느낌?

`findAllByMember`와 같은 이름만으로도 멤버의 리뷰 목록을 찾아올 거라는 느낌이 드는 것 같습니다!

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
비로그인 멤버가 조회를 하면 값을 반환하지 못하고 예외가 발생할 것 같은데 후에 멤버쪽 하시면서 처리하실 예정이신가요??

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    @Transactional
여기도 readOnly 해줘도 될 것 같네요!

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/content/ReviewImages.java
> +                           .map(reviewImage -> reviewImage.getUrl())
이런 부분도 메서드 참조로 바꿔줄 수 있을 것 같네요

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/empathy/Empathy.java
> +    }
멤버의 id를 꺼내는것이 아니라 메서드를 보내는 건 어떨까요?? 그리고 굳이 if 문을 두지 않아도 처리 가능해 보입니다!

2022-03-31 07:57 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/Review.java
> +    }
이 부분에 대한 단위테스트도 있으면 좋겠네요

2022-03-31 10:43 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    public List<ReviewGetByMemberResponseDto> findReviewsByMember(ReviewGetByMemberRequestDto reviewGetByMemberRequestDto) {
그게 맞는 거 같네요!! 리뷰 패키지 안에 있으니 그렇게 하는 게 중복을 줄일 수 있을거 같네요!!

2022-03-31 15:22 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +    }
로그인 여부 상태는 멤버에서 처리하는게 나을 거 같습니다!

2022-04-01 05:10 UTC, KJunseo approved these changes
고생하셨습니다! 이만 approve 할게요 코멘트 하나 남긴 부분만 확인해주세요!
코멘트 하나랑 conflict만 해결하시면 될 것 같네요!

2022-04-01 05:10 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/member/domain/Member.java
> +    }
같은 클래스이므로 get 대신 .id로 비교하는게 좋아보여요


```suggestion
    public boolean isSame(Member member) {
        return id.equals(member.id);
    }
```

2022-04-01 06:46 UTC, gomster96 approved these changes
엄청 많이 잘 진행하신거같아요! 

저도 잘 따라가겠습니다. 수고하셨습니다.

2022-04-01 06:46 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/domain/repository/ReviewRepository.java
> +    Page<Review> findAllByReviewContentAndTipContaining(@Param("keyword") String keyword, Pageable pageable);
제가 찾아보니까 이렇게도 사용해 볼 수 있을거같은데 한번 확인해주세요! (저는 이상하게 안돌아가네욥... ㅜ ) 

```java
Page<Review> findALlByReview~~Like
```

이렇게 해서 해보려고헀는데, 생각해보니 ReviewContent의 Contet라 안될거같긴하네요. 아무튼 이렇게 Like로도 할 수 있다는걸 새로 배워서 공유합니다.

2022-04-01 09:22 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/repository/ReviewRepository.java
> +    Page<Review> findAllByReviewContentAndTipContaining(@Param("keyword") String keyword, Pageable pageable);
감사합니다:)

2022-04-01 11:00 UTC, merged