가게 목록 조회 api 구현
RE-BON/ReBoN pull request #88
Opened 2022-03-29 21:16 UTC by KJunseo

### Description
**나름 테스트도 짜보고 해서 값은 올바르게 나오는 것 같은데, 놓친 예외가 있을 수도 있으니 그 부분 집중해서 봐주시면 감사하겠습니다. 추가적으로 sql 부분도 부탁드립니다.**

- 가게 목록을 가져오는 기능 구현
- paging과 기본적인 sorting 적용
- queryDSL로 작성한 쿼리 테스트 
- 인수 테스트

request
- tag (필수)
- category (필수)
- List<Category> (선택)

response
- id
- name
- star
- tags(id, name)
- image

### Trouble Shooting
- oneToMany가 2개 이상일 때 모든 oneToMany에 fetch join을 할 수 없다.
- queryDSL 사용시 from 절에 Q엔티티들을 나열하면 cross join이 일어난다.
- distinct를 걸어주면 일단 메모리에 올린다음 중복을 제거한다.

### ETC
- 프로젝션을 사용해보려고 했으나 페이징 적용시 값이 잘 나오지 않아 엔티티로 반환 받음.

2022-03-30 05:01 UTC, PyeongGangKim requested changes
가게 부분이 많이 복잡한데, 구현하시느라 고생많으셨습니다!!
몇가지 리뷰를 남겨봤어요 확인하시고 다시 리뷰 요청 부탁드려요:)

추가로, test를 돌려보고 싶었는데, 제가 pull 당겨온 거에서는 Tag를 인식을 못하네요,,,package 경로도 잘 명시되어 있는데 resolve를 못한다고 되어있네요,,

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/application/dto/request/ShopRequestDto.java
> +}
해당 class는 사용하고 있지 않는 클래스네요!

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +                      .collect(Collectors.toList());
application 단에서 presentation단을 알고, 참조하고 있는데, service class에서 참조하는 것이 아닌, 한 곳에서 application Dto를 presentation Dto로 변경시켜주는 것은 어떤가요??

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +    @Transactional(readOnly = true)
readOnly를 사용하면 어떤 일이 생기죠??

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/application/dto/response/ShopTagResponse.java
> +}
사용되지 않는 거 같아요!!

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopImage.java
>  public class ShopImage {
여기에도 BaseEntity extends하면 좋을 거 같아요!

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopScore.java
> +    }
가게의 점수는 리뷰 점수들의 평균인가요??

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustomImpl.java
> +    public Page<Shop> searchShopByConditionApplyPage(ShopSearchCondition condition, Pageable pageable) {
반환형을 Page<Shop>와 List<Shop>으로 했을 때, 차이가 어떤 게 있나요?

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustomImpl.java
> +    }
tagEq로 함수명을 바꾸는 게 나을 거 같아요!!

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustomImpl.java
> +                                           .leftJoin(shop.shopImages.shopImages, shopImage)
tag값과 category들과 shopimage들은 lazyLoading으로 가져오기 위해서, fetch join을 사용하지 않은 건가요?

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustomImpl.java
> +                                           .where(categoryEq(condition.getCategory())
shop.domain 패키지에 Qshop을 찾을 수 없는데, 이건 QueryDsl설정을 하면, 자동으로 만들어 지는 건가요???

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/shop/ShopIntegrationTest.java
> +    }
tag가 없는 가게도 만들어 질 수 있나요?

2022-03-30 05:01 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/shop/ShopReadAcceptanceTest.java
> +        // when
인수테스트를 진행하셔서, 통합 테스트는 따로 진행을 안한건가요??

2022-03-30 07:26 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/dto/response/ShopTagResponse.java
> +}
엇 이 부분은 `ShopSimpleResponse`에서 사용하고 있습니다!!

2022-03-30 07:28 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/dto/request/ShopRequestDto.java
> +}
굿굿

2022-03-30 08:02 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +                      .collect(Collectors.toList());
application -> presentation 의존은 끊어주었습니다!
저같은 경우는 dto 변환작업은 각 dto 내에서 처리하게 해주었습니다! 왜냐하면 한 곳에서 처리하게 하면 dto들이 많아질수록 클래스가 너무 비대해져 찾기 힘들 것 같다는 생각이 들었고, 변환작업 정도는 dto에서도 처리해도 된다는 생각이었습니다!

2022-03-30 08:03 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/ShopService.java
> +    @Transactional(readOnly = true)
readOnly를 사용하면 아래와 같은 일이 생깁니다!
1) 해당 트랜잭션 내 읽기 작업 이외의 작업이 일어나면 예외발생
2) 더티체킹 하지 않음 -> 성능상 이점
3) 후에 replication 적용 시 slave db로 보낼 요청 거르는 용도

2022-03-30 08:07 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopScore.java
> +    }
그렇게 처리해야 할 것 같습니다! 이 부분은 
리뷰 생성 -> shop의 star 변경 하는식으로 처리해야할 것 같습니다

2022-03-30 08:09 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustomImpl.java
> +    public Page<Shop> searchShopByConditionApplyPage(ShopSearchCondition condition, Pageable pageable) {
Page로 받는다면 데이터의 총 개수나 전체 페이지 수와 같은 page와 관련된 정보까지 얻어올 수 있습니다. 프론트에서 필요하다고 하면 response에 추가해서 보내주면 될 것 같습니다!

2022-03-30 08:14 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustomImpl.java
> +                                           .leftJoin(shop.shopImages.shopImages, shopImage)
oneToMany가 2개 이상일 때 모든 oneToMany에 fetch join을 할 수 없었습니다.
-> MultipleBagFetchException 발생(카테시안 곱으로 인해 중복이 너무 많아 사전에 미리 차단하는 것 같습니다)

참고: https://jojoldu.tistory.com/457

쿼리에서는 조건만 걸어주고 batch size 옵션을 줬습니다!(지금 보니 test 프로퍼티파일에만 batch size를 줬었네요 ㅎ..)

2022-03-30 08:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustomImpl.java
> +                                           .where(categoryEq(condition.getCategory())
build.gradle에 필요한 의존성 설정을 해주고 아래 명령어를 실행하면 됩니다!
`./gradlew clean compileQuerydsl`

`build - generated - querydsl` 하위에 Q클래스가 생깁니다

2022-03-30 08:17 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/shop/ShopIntegrationTest.java
> +    }
이 부분은 사용하지 않는데 지우질 않았네요 ㅎ..

2022-03-30 08:19 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/shop/ShopReadAcceptanceTest.java
> +        // when
원래 통합테스트를 진행했었습니다. 그러나 피그마를 보면서 다시 보니, request 값이 초기에 생각하던 것과 좀 달라서 잘못된 테스트를 진행했었습니다. 

지금은 인수테스트를 진행한 상태여서 기존에 통합테스트로 커버하던 로직들을 인수테스트로 커버할 수 있게 되면서 잘못된 통합테스트만 지우고 새로 통합테스트를 작성하지는 않았습니다.

2022-03-30 08:21 UTC, gomster96 requested changes
수고하셨습니다.! 몇가지 질문사항에 코멘트 달아주시면 확인하고 Approve하겠습니다.!

2022-03-30 08:21 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/application/dto/response/ShopSimpleResponseDto.java
> +                                         .collect(Collectors.toList());
from이란 메서드명으로, dto를 생성해주는 로직을 수행할 때 주로 사용하나요?

2022-03-30 08:21 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +    public Category(String name, Category parent) {
음 parent 가 없는 부분은 어차피 null이라도 이렇게 해주니 중복될 코드를 줄일 수 있겠네요

2022-03-30 08:21 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopImages.java
> +                         .orElseThrow();
여기서 orElseThrow를 사용하셨는데, 따로 Exception 클래스를 만들어주시지 않고 Throw를 보내신 이유가 있을까요? 
위에서 보니 이  mainImage()메서드는 shop에서 mainImage를 받아올때 사용하는 거 같은데,  샵이미지에 메인이미지가 없을 경우도 있을 거 같긴 한데, 제 생각에는 그때 null 이 가던지 뭐 이런 처리가 필요할거같은데, 어떤 처리가 되어있는지 궁금합니다. orElseThrow()를 인자값 없이 보내면 어떻게 되는건가요?

2022-03-30 08:21 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustom.java
> +}
따로 ShopRepositoryCustom이라고 interface를 생성한 것이, QueryDSL을 사용하기 위한 분리인것인가요?

2022-03-30 08:21 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/ShopSearchCondition.java
> +        this(tag, category, Collections.emptyList());
Collections.emtpyList()로 처음부터 비어있는 서브카테고리이기때문에 add와 get을 사용할 수 없도록 이렇게 막아주는 코딩방식 너무 좋네요

2022-03-30 08:26 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/application/dto/response/ShopSimpleResponseDto.java
> +                                         .collect(Collectors.toList());
dto를 생성해주는 메서드를 뜻하기 보다는 정적 팩토리 메서드의 네이밍 형식입니다!

https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/
참고해보시면 좋을 것 같아요!

2022-03-30 08:26 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +    public Category(String name, Category parent) {
넵 보통 생성자를 여러개 사용할 경우는 주 생성자만 할당을 해주고 나머지 부 생성자는 this()를 통해 주생성자를 호출하는 식으로 처리합니다!

2022-03-30 08:33 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopImages.java
> +                         .orElseThrow();
👍🏻 놓치고 있었네요. 이 경우는 서버에 '이미지가 없습니다'와 같은 기본 이미지를 저장해두고 main 이미지가 없다면 기본 이미지를 반환해주는 식으로 처리하는 게 좋을 것 같네요!

현재 이미지 관련 기능은 구현되지 않았기 때문에 상수로 임시 처리해놓겠습니다!

2022-03-30 08:37 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/repository/ShopRepositoryCustom.java
> +}
맞습니다. 네이밍 형식으로 알고 있습니다

2022-03-31 05:37 UTC, PyeongGangKim approved these changes
복잡한 가게 하느라 고생많으셨습니다:)
많이 배웁니다!! approve할게요!

2022-03-31 05:37 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/shop/domain/like/Likes.java
> +public class Likes {
class명을 바꾸신 이유가 따로 있으실까요?

2022-03-31 05:37 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    }
Custom Exception을 만들어져도 좋을 거 같아요!!
ex) TagNotFoundException

2022-03-31 05:37 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/acceptance/admin/AdminCategoryRegister.java
> +    }
람다를 잘 쓰시네요!! Fuction.identity 배우고 갑니다!

2022-03-31 05:56 UTC, gomster96 approved these changes
수고하셨습니다! 짜신 코드보면서 저도 많이 배우게되네요

2022-03-31 05:56 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/shop/domain/content/ShopImages.java
> +                         .orElseGet(() -> DEFAULT_IMAGE_URL);
오 디폴트이미지 URL 을 주는 처리방식 좋네요

2022-03-31 07:21 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/shop/domain/like/Likes.java
> +public class Likes {
테스트 격리를 할때 `@Entity`어노테이션이 붙어있는 클래스명을 가져와서 처리를 해주게 했는데, Like 같은 경우 테이블이 Likes로 만들어지고 있어서 제대로 처리가 안되어있었어요. 하드코딩으로 추가해도 되겠지만 크게 영향을 줄 거 같지 않아서 그냥 클래스 명을 변경했습니다!

2022-03-31 07:22 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    }
이 부분은 Tag 쪽이라서 일단 Shop에 필요한 부분을 임시적으로 만든 거라 별도 처리를 하지 않았습니다!

2022-03-31 07:22 UTC, merged