[#95] 삭제되지 않은 리뷰 조회
RE-BON/ReBoN pull request #96
Opened 2022-04-02 16:04 UTC by PyeongGangKim

### Description
- 리뷰 조회를 삭제되지 않은 리뷰 조회로 변경
- search하는 것을 querydsl로 변경.

### Trouble Shooting
- isDeleted가 BaseEntity에서 private으로 설정이 되어있어, Jpql에서 review로 바로 접근이 불가능하다 -> querydsl를 사용하여 해결

### ETC

2022-04-03 10:18 UTC, KJunseo requested changes
고생하셨습니다! 리뷰 남겼어요

2022-04-03 10:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +            List<Review> reviews = reviewRepository.findAllByReviewContentAndTipContainingAndIsDeletedFalse(
메서드 이름이 너무 길다고 생각해요.
어떤 역할을 하는지 구체적으로 모두 적어줘도 좋지만, 한 눈에 들어오기 어렵고, spring data jpa가 아닌 임으로 만드는 메서드라면 좀 더 추상적인 이름을 사용해도 좋다고 생각해요.
spring data jpa도 이름이 너무 길면 가독성이 좋지 않아 그런 부분도 문제점으로 알고있어요.

2022-04-03 10:18 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/domain/repository/ReviewRepository.java
> +    Optional<Review> findByIdAndIsDeletedFalse(Long id);
저도 이번에 찾아보면서 알게된 부분인데, 이렇게 모든 필드에 deleted를 검사하기 보다 `@SQLDelete `를 사용해보는건 어떤가요?

아래 링크를 참고해서 구현해도 좋을 것 같아요
https://www.baeldung.com/spring-jpa-soft-delete

2022-04-03 11:09 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +            List<Review> reviews = reviewRepository.findAllByReviewContentAndTipContainingAndIsDeletedFalse(
저도 메서드 이름을 지으면서, 가독성이 떨어진다고 생각했는데, 좀 더 가독성 높은 메서드 명을 생각해봐야겠네요!!
감사합니다:)

2022-04-03 11:09 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/review/domain/repository/ReviewRepository.java
> +    Optional<Review> findByIdAndIsDeletedFalse(Long id);
오~!!
감사합니다!! 한번 읽어보고 참고할게요!!

2022-04-03 15:21 UTC, gomster96 approved these changes
네이밍만 조금 바꾸시면 괜찮을것 같습니다.

수고하셨습니다!

2022-04-03 15:21 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +            List<Review> reviews = reviewRepository.findAllByReviewContentAndTipContainingAndIsDeletedFalse(
어어.... 상당히 길긴하네요. 그냥 findAllReviewByKeyword 이런식으로 해도 좋을거같아요

2022-04-05 05:31 UTC, KJunseo approved these changes
approve 하겠습니다! 고생하셨습니다!
그래도 마지막으로 리뷰 남긴 거 확인 부탁드립니다

2022-04-05 05:31 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/review/application/ReviewService.java
> +
필요없는 부분인 것 같습니다!

2022-04-05 05:31 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewReadIntegrationTest.java
>  public class ReviewReadIntegrationTest extends ReviewIntegrationTest {
어제 말씀드린 부분을 생각해봤는데, 통합테스트에서는 review를 생성할 때 몇개의 리뷰의 deleted 값을 true로 주입해줘서 생성 후(직접 repository) deleted가 아닌 review만 가져오는지 확인해보는 식으로 테스트 할 수 있을 것 같습니다. 

이런 부분을 위해서 생성자 의존성 주입을 하기도 하니 이 방법이 괜찮을 것 같다는 생각이듭니다.

2022-04-05 05:31 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewReadIntegrationTest.java
>          //given
현재 given이 너무 길어서 가독성이 떨어지는 것 같은데 메서드 분리 같은 걸 하는 것도 좋아보여요

2022-04-06 12:28 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/review/ReviewReadIntegrationTest.java
>  public class ReviewReadIntegrationTest extends ReviewIntegrationTest {
지금 생각해보니까, deleted field가 default로 false로 만들어지고, 해당 class에 생성자나 setter가 없어서, true로 주입을 할 수 있을까요? 테스트를 위해, 생성자나 setter로 만드는 것도 아닌거 같아서요,,

2022-04-10 16:54 UTC, merged