[#14] 태그 조회 기능
RE-BON/ReBoN pull request #98
Opened 2022-04-04 08:17 UTC by leehyelim0691

### Description
[#14] 태그 조회 기능

### Trouble Shooting

### ETC

2022-04-07 04:13 UTC, KJunseo requested changes
고생하셨습니다! 리뷰 확인후 재요청 주세요!

2022-04-07 04:13 UTC, KJunseo commented on backend/src/docs/asciidoc/api.adoc
> +|===
어떤 API인지도 적어주면 좋을 것 같아요 (ex. `=== 전체 Tag 조회`)

이번에 개발한 부분은 전체 태그를 가져오는 기능인 것 같아서 파라미터 부분이 필요없을 것 같아요.(GET `/api/tags`)

추가적으로 스니펫이 include가 되어 있지 않아서 문서화가 이루어지지 않고 있습니다!

2022-04-07 04:13 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    }
`@Transactional(readOnly = true)`를 붙여주는 건 어떤가요?

2022-04-07 04:13 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/presentation/dto/TagAssembler.java
> +    }
메서드 명이 어울리지 않는 것 같습니다.
태그관련 기능인데 메서드명이 카테고리 관련이에요

2022-04-07 04:13 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
현재 `@Getter`를 붙여줬는데 따로 getter를 만드신 이유가 있나요?

2022-04-07 04:13 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/tag/TagReadAcceptanceTest.java
> +        });
api 요청의 결과값이 TagResponse여서 List<TagResponse>로 받아주는게 좋아보입니다.

2022-04-07 04:13 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagCreateIntegrationTest.java
> +@Transactional
최상위 부모인 IntegrationTest에 이미 `@SpringBootTest`, `@Transactional`가 붙어져있는데 따로 붙여주신 이유가 있을까요??

TagIntegrationTest와 TagReadIntegrationTest에도 붙어져있는데 확인 부탁드려요!

2022-04-07 04:13 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagReadIntegrationTest.java
> +    public void findAllTags() {
모든 태그 조회가 되는지 확인하기 위한 테스트로는 태그 하나만 생성하는 것 보다 태그를 좀 더 생성하고, 사이즈가 맞게 나오는지도 검증하면 좋을 것 같아요.

2022-04-07 05:32 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    }
앗 네 좋은 의견 감사합니다!!

2022-04-07 05:33 UTC, PyeongGangKim requested changes
고생많으셨습니다!!
리뷰 달았으니 확인 부탁드려요!!

2022-04-07 05:33 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/tag/TagReadIntegrationTest.java
> +    public void findTagById() {
id가 없을 때, exception 나는 것도 체크하면 좋을 거 같아요!!

2022-04-07 05:33 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/tag/TagCreateIntegrationTest.java
> +        // given
함수명이 존재하는 태그를 생성한다라고 느껴져요!! exception이 난다거나 중복이 되면 생성할 수 없다라는 의미가 들어가면 좀 더 좋을 거 같아요!!

2022-04-07 05:33 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
>  }
TagIdException을 만드셨으니까, TagIdException을 사용하는 게 좋아보여요!!

2022-04-07 05:33 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    }
Tags 패키지 내에 있으니, Tags를 굳이 명시해 주지 않고, findAll로 해주는 것은 어떤가요?
추가적으로 36번째 줄에 있는 findAll가 반환값만 다르고 동일한 역할을 하는 것 같아요!!

2022-04-07 05:36 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/presentation/dto/TagAssembler.java
> +    }
앗 네 제가 실수 했었네요 감사합니다!

2022-04-07 06:32 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
TagService에서  Tag의 id 값을 받아와야 하는 부분이 있어서 넣었는데 혹시 이렇게 하면 안좋은 걸까요!?

2022-04-07 06:41 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/acceptance/tag/TagReadAcceptanceTest.java
> +        });
아 혹시 지금도 list로 받아지고 있는게 아닌가요?!ㅠ 정확히 어떻게 바꾸어야 할지 모르겠습니다ㅠ!

2022-04-07 07:27 UTC, leehyelim0691 commented on backend/src/docs/asciidoc/api.adoc
> +|===
앗 네! 다른 코드 수정후에 다시 Docs 작성하겠습니다!

2022-04-08 02:46 UTC, gomster96 requested changes
수고하셨습니다. 위에 분들이 잡아주신  부분들 조금만 고쳐주시고 올리면 될거같아요.

2022-04-08 02:46 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/tag/domain/repository/TagRepository.java
> +    List<Tag> findTags();
현재 이 메서드는 새로 만들필요 없고 그냥 서비스 단에서 tagRepository.findAll() 을 사용하시면 될거같아요

2022-04-08 02:46 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagReadIntegrationTest.java
> +        assertThat(tags.getName()).isEqualTo(tagName);
//when //then 위치가 주석에 따라 잘 구별되면 좋을거같아요

2022-04-08 02:46 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
@getter 를 찾아보시면 중복된 코드라는걸 알 수 있을거에요!

2022-04-08 03:15 UTC, KJunseo requested changes
리뷰남겼습니다!
한 번 더 확인 부탁드립니다!

2022-04-08 03:15 UTC, KJunseo commented on backend/src/docs/asciidoc/api.adoc
문서가 아에 없는것 같아요 ㅠㅠ
아래 가게 조회 처럼 스니펫을 추가해줘야할 것 같습니다.

2022-04-08 03:15 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/tag/domain/Tag.java
> +    }
`@Getter`를 붙이면 보이지는 않지만 자동으로 필드에 맞는 getter가 생성됩니다.
실제로 저 메서드 이름을 cmd + 클릭 해보시면 아무곳에서도 사용하고 있지 않습니다.

2022-04-08 03:15 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/tag/TagReadAcceptanceTest.java
> +        });
인수테스트는 요청부터 반환까지를 테스트하는 것입니다.
`GET /api/tags`라는 요청을 보냈을 때 `List<TagResponse>` 타입을 받는 걸 원하는데 현재는 그냥 도메인으로 받아오고 있습니다.(`List<Tag>`)

```suggestion
        List<TagResponse> result = response.as(new TypeRef<>() {
        });
```

2022-04-08 03:15 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
>  @Transactional
TagIntegrationTest도 IntegrationTest를 상속받고 있습니다.
따라서 중복해서 어노테이션을 붙여 줄 필요는 없어보입니다.

2022-04-08 03:15 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagReadIntegrationTest.java
> +
두 줄이네요!

2022-04-08 03:27 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/domain/repository/TagRepository.java
> +    List<Tag> findTags();
이 부분은 현재 지워졌는데, 잘못 올라간 것 같습니다ㅠ 감사합니다!

2022-04-08 03:46 UTC, PyeongGangKim approved these changes
위에 분들이 남기신 리뷰랑 제가 남기 리뷰만 확인하면 될거 같아요!!
고생많으셨습니다!!

2022-04-08 03:46 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    }
findAll과 findTags를 나누신 이유가 있는건가요?

2022-04-08 03:46 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/tag/presentation/dto/TagAssembler.java
> +                .map(tag -> new TagResponse(tag.getId(), tag.getName()))
List를 반환하니까 tagResponses라고 복수로 써주는 건 어떨까요??

2022-04-08 12:24 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagReadIntegrationTest.java
> +        assertThat(tags.getName()).isEqualTo(tagName);
이 부분도 현재 지워졌는데, 잘못 올라간 것 같습니다! 감사합니다!

2022-04-08 12:35 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/presentation/dto/TagAssembler.java
> +                .map(tag -> new TagResponse(tag.getId(), tag.getName()))
좋은 의견 감사합니다!

2022-04-11 05:37 UTC, leehyelim0691 commented on backend/src/main/java/com/handong/rebon/tag/application/TagService.java
> +    }
findAll은 shop 조회 기능 할 때 필요해서 준서님이 만들어 두신 걸로 압니다! 나중에 삭제 할 예정입니다!

2022-04-11 09:17 UTC, KJunseo approved these changes
이번에는 이만 approve할게요!
머지하시기 전에 코멘트 하나 남긴 것만 확인해주세요!
conflict 제거하시고 로컬에서 실제 실행 & 테스트 잘 돌아가면 dev에 머지하시면 될 것 같습니다!

2022-04-11 09:17 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
>  @Transactional
IntegrationTest를 상속받고 있습니다.
IntegrationTest에는 `@Transactional`이 붙어있어요. 혹시 여기 따로 붙여두신 이유가 있나요?

2022-04-11 11:24 UTC, leehyelim0691 commented on backend/src/test/java/com/handong/rebon/integration/tag/TagIntegrationTest.java
>  @Transactional
앗 아니요 제가 깜빡하고 지우지 않은 것 같습니다ㅠ 감사합니다!

2022-04-11 11:30 UTC, merged