[#14] Category 조회 API 구현
RE-BON/ReBoN pull request #99
Opened 2022-04-04 11:31 UTC by gomster96

### Description
Root 카테고리들의 배열과, 각 RootCategory 들의 Children에는 자식 카테고리들의 배열을 리턴하도록 API 를 구현하였다. 

### Trouble Shooting

### ETC

2022-04-04 14:05 UTC, PyeongGangKim requested changes
고생하셨습니다!!
리뷰 몇 가지 남겼습니다. 확인하시고 다시 리뷰 요청해주세요:)

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
두줄입니다:)

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
두줄입니다:)

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +        return categoryRepository.findAllById(subCategories);
entity를 application단으로 바로 넘기는 건 좋아보이지 않아요!!
Response DTO만들어줘서, 넘겨주는 게 좋을 거 같아요!

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/category/application/dto/response/RootCategoryResponse.java
> +    }
따로 메서드로 분리해서 만들어주는 게 좋을 거 같아요!!
constructor에는 변수 할당만 해주는 것이 좋을 거 같아요

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +    public List<Category> findSubCategoryByIds(List<Long> subCategories) {
@Transactional이 필요할 거 같아요!! 다른 부분도 살펴보시면 좋을 거 같아요!

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/exception/category/CategoryIdException.java
> +        super("존재하지 않는 category id값을 요청하였습니다.", HttpStatus.BAD_REQUEST);
`public class CategoryIdException extends CategoryException {`

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/main/java/com/handong/rebon/category/presentation/ApiCategoryController.java
> +        List<RootCategoryResponse> responses = categoryService.findRootCategoriesAndChildren();
이 부분도 format이 맞지 않아요~

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/unit/category/domain/CategoryTest.java
> +
두 줄입니다:)

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/category/CategoryCreateIntegrationTest.java
> +        Long parentId = categoryService.create(parentName);
다른 부모 카테고리에서 같은 이름의 카테고리를 생성하는 성공하는 test도 잇으면 좋을 거 같아요!!

2022-04-04 14:05 UTC, PyeongGangKim commented on backend/src/test/java/com/handong/rebon/integration/category/CategoryReadIntegrationTest.java
> +        //when
이 부분은 왜 필요한 건 가요??

2022-04-05 05:17 UTC, KJunseo requested changes
리뷰할 양이 그렇게 많지는 않네요!
고생하셨습니다! 몇가지 리뷰 남겼어요!
추가적으로 pr전에 포맷팅을 하시는 걸 권장드립니다!

2022-04-05 05:17 UTC, KJunseo commented on backend/src/docs/asciidoc/api.adoc
> +|===
필요없는 부분인 것 같아요!

2022-04-05 05:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/application/dto/response/RootCategoryResponse.java
> +    }
생성자 내에서는 간단한 검증이나 값 할당만 이루어지는게 좋을 것 같아요.
변환이 필요한 경우 정적 팩토리 메서드와 같은 별도의 메서드로 분리하는게 좋을 것 같아요

2022-04-05 05:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +    public List<RootCategoryResponse> findRootCategoriesAndChildren() {
`@Transactional(readOnly=true)`작업을 해주는 것이 좋아보입니다.

2022-04-05 05:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/application/dto/response/ChildCategoryDto.java
> +    }
변수와 생성자 사이에 공백을 두는 것이 좋아보입니다.
추가적으로 생성자의 `{` 부분 전에 띄어쓰기가 필요해 보입니다.
pr전에 단축키를 이용해 포맷팅을 해주는 작업이 필요해보여요.

2022-04-05 05:17 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +
저희가 컨벤션으로 정해놓은 선언 순서는
```java
    상수
    클래스 변수
    인스턴스 변수
    생성자
    팩토리메서드
    메서드
    기본 메서드(equals, hashCode, toString...)
```
입니다.
getter와 같은 경우 기본 메서드로 볼 수 있습니다. 따라서 하단으로 내리는 게 좋아보입니다.

2022-04-05 05:17 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/acceptance/category/CategoryReadAcceptanceTest.java
> +        Assertions.assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
어떤 값이 넘어왔는지도 모든 값을 비교할 필요는 없지만 몇 개의 값은 확인해줘도 좋을 것 같아요

2022-04-05 05:17 UTC, KJunseo commented on backend/src/test/java/com/handong/rebon/integration/category/CategoryReadIntegrationTest.java
> +                                                       .contains("한식", "양식", "중식", "프렌차이즈", "퓨전한식");
containsOnly 같은걸 쓰면 더 정확할 것 같아요

2022-04-05 06:49 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
앗... 포매터를 적용하고 올리는걸 습관화 하겠습니다. 감사합니다.

2022-04-05 06:49 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
앗... 포매터를 적용하고 올리는걸 습관화 하겠습니다. 감사합니다.

2022-04-05 06:58 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/application/dto/response/RootCategoryResponse.java
> +    }
감사합니다. Assembler 를 사용해보겠습니다.

2022-04-05 07:54 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/integration/category/CategoryCreateIntegrationTest.java
> +        Long parentId = categoryService.create(parentName);
unit 테스트에 해당 테스트 존재합니다. 감사합니다!

2022-04-05 07:58 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/integration/category/CategoryReadIntegrationTest.java
> +        //when
사실 테스트를 하는데 크게 필요하지 않습니다.. ㅎㅎㅎ 그냥 뭔가 다양한 꼴을 만들어주려고 했었는데 지우도록 하겠습니다. 감사합니다!

2022-04-06 05:08 UTC, KJunseo approved these changes
고생하셨습니다! 저는 이만 approve하겠습니다.

2022-04-06 05:08 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/presentation/dto/CategoryAssembler.java
> +                             .map(rootCategory -> new RootCategoryResponse(rootCategory.getId(), rootCategory.getName(), childCategoryResponses(rootCategory.getChildren())))
이 라인이 너무 긴거같아요. 가능하면 인텔리제이에서 잡아주는 기준선을 넘지 않는게 좋아보여요.
categoryAssembler도 확인 부탁드립니다.

<img width="993" alt="스크린샷 2022-04-06 오후 2 02 12" src="https://user-images.githubusercontent.com/45876793/161899384-d745c7e8-61dc-400d-a26a-7e5cbcf0e2e5.png">

2022-04-06 05:08 UTC, KJunseo commented on backend/src/main/java/com/handong/rebon/category/presentation/dto/response/ChildCategoryResponse.java
> +
다른 곳과의 일관성을 위해 공백을 제거해도 좋을 것 같네요

2022-04-06 08:06 UTC, PyeongGangKim approved these changes
고생많으셨습니다!!이번에는 리뷰할게 따로 없는 거 같네요!!

2022-04-07 10:04 UTC, merged

2022-04-07 10:05 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/application/CategoryService.java
> +    public List<Category> findSubCategoryByIds(List<Long> subCategories) {
감사합니다. 제가 자꾸 집중하지 않는군요! Transaction 중요한데,,, 감사합니다.!

2022-04-07 10:05 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/application/dto/response/RootCategoryResponse.java
> +    }
아 적용하겠습니다 감사합니다.

2022-04-07 10:05 UTC, gomster96 commented on backend/src/main/java/com/handong/rebon/category/domain/Category.java
> +
컨벤션 다시한번 리마인드 하겠습니다!

2022-04-07 10:06 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/acceptance/category/CategoryReadAcceptanceTest.java
> +        Assertions.assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
네넵 이번에 덕분에 좋은 방법 알았습니다!

2022-04-07 10:06 UTC, gomster96 commented on backend/src/test/java/com/handong/rebon/integration/category/CategoryReadIntegrationTest.java
> +                                                       .contains("한식", "양식", "중식", "프렌차이즈", "퓨전한식");
상세한 리뷰 감사합니다. 👍